#### Pandas + NumPy Data Cleaning — 30 Questions

In [525]:
# 1. Load the CSV using Pandas and display the first 10 rows.
import pandas as pd
df=pd.read_csv("C:\\Users\\vaish\\Downloads\\customer_data.csv")
df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.283473578603065,44108.07924936186,793.2135772820182,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.630009830989785,80888.86263734727,850.0,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.520166822399105,50011.55555812526,796.7940989517157,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30823662701,482.3950728788773,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

In [526]:
# 2. Check the number of rows and columns in the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer ID       1980 non-null   object
 1   Age               1669 non-null   object
 2   income_usd        1560 non-null   object
 3   credit Score      1640 non-null   object
 4   tenure_years      1742 non-null   float64
 5   monthly_visits    1720 non-null   float64
 6   satisfaction      1601 non-null   float64
 7   City              1700 non-null   object
 8   customer_segment  1620 non-null   object
 9   gender            1760 non-null   object
 10  is_active         1660 non-null   object
 11  churn_flag        1840 non-null   object
 12  signup_date       1760 non-null   object
 13  lead_source       1580 non-null   object
 14  notes_text        1344 non-null   object
dtypes: float64(3), object(12)
memory usage: 234.5+ KB

In [527]:
# 3. Display all column names and identify which column names contain
# leading/trailing spaces or inconsistent capitalization.
df.columns

Index(['Customer ID', 'Age ', 'income_usd', 'credit Score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'City', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [528]:
# 4. Check the data type of every column using Pandas.
df.dtypes

Customer ID          object
Age                  object
income_usd           object
credit Score         object
tenure_years        float64
monthly_visits      float64
satisfaction        float64
City                 object
customer_segment     object
gender               object
is_active            object
churn_flag           object
signup_date          object
lead_source          object
notes_text           object
dtype: object

In [529]:
# 5. Calculate the number and percentage of missing values in every column.
print(df.isnull().sum())
print(df.isnull().sum()/100)

Customer ID          20
Age                 331
income_usd          440
credit Score        360
tenure_years        258
monthly_visits      280
satisfaction        399
City                300
customer_segment    380
gender              240
is_active           340
churn_flag          160
signup_date         240
lead_source         420
notes_text          656
dtype: int64
Customer ID         0.20
Age                 3.31
income_usd          4.40
credit Score        3.60
tenure_years        2.58
monthly_visits      2.80
satisfaction        3.99
City                3.00
customer_segment    3.80
gender              2.40
is_active           3.40
churn_flag          1.60
signup_date         2.40
lead_source         4.20
notes_text          6.56
dtype: float64

In [530]:
# 6. Find the rows where Customer ID is missing.
df["Customer ID"].isna()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: Customer ID, Length: 2000, dtype: bool

In [531]:
# 7. Remove leading/trailing whitespace from all column names and convert them
# to lowercase with underscores.
df.columns=df.columns.str.strip().str.lower().str.replace(" ","_")
df.columns

Index(['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [532]:
# 8. Identify duplicate Customer ID values and count how many duplicates exist.
df["customer_id"].duplicated().sum()

19

In [533]:
# 9. Remove duplicate customer records while keeping the first occurrence.
df["customer_id"].drop_duplicates()

0       CUST-01861
1       CUST-00354
2       CUST-01334
3       CUST-00906
4       CUST-01290
           ...
1995    CUST-01131
1996    CUST-01295
1997    CUST-00861
1998    CUST-01460
1999    CUST-01127
Name: customer_id, Length: 1981, dtype: object

In [534]:
# 10.Find all unique values in the customer_segment column and identify
# inconsistent categories such as Consumer, consumer, consumer , etc.
df["customer_segment"].unique()

array(['consumer ', 'Consumer', 'Enterprise', 'SMB', nan, 'SMB.',
       'UNKNOWN'], dtype=object)

In [535]:
# 11.Clean the customer_segment column by standardizing capitalization and
# whitespace.
df["customer_segment"].str.capitalize().str.strip()

0         Consumer
1         Consumer
2         Consumer
3       Enterprise
4       Enterprise
           ...
1995      Consumer
1996           Smb
1997          Smb.
1998           Smb
1999      Consumer
Name: customer_segment, Length: 2000, dtype: object

In [536]:
# 12.Find all unique values in the gender column and convert them into consistent
# categories such as Male and Female.
df["gender"].unique()

array([nan, 'Male', 'm', 'Female', 'M', 'F', 'f'], dtype=object)

In [537]:
df["gender"].replace({"m":"Male","M":"Male","F":"Female","f":"Female"},inplace=True)

C:\Users\vaish\AppData\Local\Temp\ipykernel_11168\1429202342.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["gender"].replace({"m":"Male","M":"Male","F":"Female","f":"Female"},inplace=True)

In [538]:
df["gender"]

0          NaN
1         Male
2         Male
3         Male
4         Male
         ...
1995      Male
1996      Male
1997    Female
1998       NaN
1999       NaN
Name: gender, Length: 2000, dtype: object

In [539]:
# 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and
# No, no, N, 0 become 0.
df["is_active"].replace({"Yes":1,"yes":1,"Y":1,"No":0,"no":0,"N":0},inplace=True)
df["is_active"]

C:\Users\vaish\AppData\Local\Temp\ipykernel_11168\3891680893.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["is_active"].replace({"Yes":1,"yes":1,"Y":1,"No":0,"no":0,"N":0},inplace=True)

0         1
1       NaN
2         1
3         0
4         1
       ...
1995      0
1996      0
1997      1
1998      0
1999      1
Name: is_active, Length: 2000, dtype: object

In [540]:
# 14.Convert the churn_flag column from categorical values (Yes/No) into a binary
# numerical column (1/0).
df["churn_flag"].replace({"Yes":1,"No":0},inplace=True)
df["churn_flag"]

C:\Users\vaish\AppData\Local\Temp\ipykernel_11168\1985248510.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["churn_flag"].replace({"Yes":1,"No":0},inplace=True)
C:\Users\vaish\AppData\Local\Temp\ipykernel_11168\1985248510.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["churn_flag"].replace({"Yes":1,"No":0},inplace=True)

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1995    0.0
1996    1.0
1997    0.0
1998    1.0
1999    0.0
Name: churn_flag, Length: 2000, dtype: float64

In [541]:
# 15.Identify all values in income_usd that cannot be directly interpreted as
# numbers.
df["income_usd"].astype(str).str.replace(",","").str.replace("$","").str.strip()

0        28198.41033378447
1        61312.83129054326
2        44199.67123886594
3        56259.90961066413
4       31238.641956219115
               ...
1995     79436.89335323017
1996    39912.379910506046
1997    24522.265445928326
1998     84103.61055756662
1999     53723.87392391664
Name: income_usd, Length: 2000, dtype: object

In [542]:
df["income_usd"]=pd.to_numeric(df["income_usd"],errors="coerce")
df["income_usd"].dtype

dtype('float64')

In [543]:
# 17.Clean the Age column so values such as "35 years" become numeric values.
df["age"]=pd.to_numeric(df["age"],errors="coerce")

In [544]:
# 18.Identify unrealistic age values using NumPy/Pandas and replace them with
# NaN.
import numpy as np
df["age"]=[np.nan if i<0 or i>100 else i for i in df["age"]]
df["age"]

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998          NaN
1999    59.256095
Name: age, Length: 2000, dtype: float64

In [545]:
# 19.Clean the credit_score column by removing text such as "pts" and converting
# the column to numeric.
df["credit_score"]=df["credit_score"].str.replace("pts","")
df["credit_score"]

0       660.5629175986682
1                    838
2       613.1327753975876
3       720.2369862405794
4        549.183252322903
              ...
1995    633.9740063023814
1996    701.7201056433207
1997    647.7993363128053
1998                 521
1999     576.739073460913
Name: credit_score, Length: 2000, dtype: object

In [546]:
df["credit_score"]=pd.to_numeric(df["credit_score"],errors="coerce")

In [547]:
# 20.Detect outliers in income_usd using the IQR method with NumPy/Pandas.
df["income_usd"]=pd.to_numeric(df["income_usd"],errors="coerce")
q1=df["income_usd"].quantile(0.25)
q2=df["income_usd"].quantile(0.75)
IQR=q2-q1
df[(df["income_usd"]<(q1-1.5*IQR)) | (df["income_usd"]>(q2+1.5*IQR))]

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
65,CUST-01848,24.580330,248156.714139,599.236543,7.687234,NaN,NaN,Bengaluru,NaN,Male,1,0.0,26/02/2026,NaN,late payment
101,CUST-00994,NaN,204783.981770,NaN,4.016700,2.0,2.730604,NaN,UNKNOWN,Female,0,1.0,2023-10-09,Social,normal
116,CUST-01104,44.235927,785035.670283,665.763448,3.276726,10.0,NaN,Chennai,Consumer,NaN,NaN,0.0,2024-01-29,website,ok
137,CUST-01906,NaN,211200.518666,615.126374,7.559306,7.0,NaN,Pune,NaN,NaN,NaN,0.0,2026-04-26,Email,VIP
141,CUST-00307,33.986526,159459.956802,661.014409,14.559882,11.0,2.099117,Hyderabad,NaN,Female,1,0.0,2021-11-08,referral,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1846,CUST-00201,NaN,327022.958154,618.323201,4.895690,7.0,3.026481,Delhi,NaN,Male,0,0.0,23/07/2021,NaN,normal
1852,CUST-01514,18.000000,795063.796842,658.993309,5.103205,2.0,NaN,Chennai,Enterprise,NaN,0,0.0,2025-03-22,Unknown,NaN
1914,CUST-01586,18.549038,168194.079680,590.000000,7.839547,NaN,4.001705,Hyderabad,SMB,Male,0,0.0,2025-06-04,NaN,follow-up needed
1918,CUST-00776,40.433567,234262.106128,644.176226,5.995918,8.0,2.238018,Delhi,SMB,Female,0,1.0,2023-03-01,NaN,normal
1936,CUST-00167,49.178876,258343.545730,585.240778,6.889842,9.0,3.986674,Delhi,SMB,Female,0,1.0,2021-06-19,Referral,NaN

In [548]:
# 21.Detect outliers in credit_score using the IQR method.
df["credit_score"]=pd.to_numeric(df["credit_score"],errors="coerce")
q1=df["credit_score"].quantile(0.25)
q2=df["credit_score"].quantile(0.75)
IQR=q2-q1
df[(df["credit_score"]<(q1-1.5*IQR)) | (df["credit_score"]>(q2+1.5*IQR))]

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
62,CUST-01622,38.558690,NaN,404.916112,4.809390,9.0,3.309774,Pune,Enterprise,Female,NaN,0.0,2025-07-10,???,NaN
348,CUST-01511,38.814958,72836.889976,395.344523,5.204901,6.0,3.133335,Delhi,Enterprise,NaN,1,0.0,2025-03-19,WEB,good customer
377,CUST-01757,58.519327,49302.549987,372.537221,1.627648,NaN,NaN,Chennai,Consumer,Male,1,0.0,2025-11-25,referral,NaN
422,CUST-01360,NaN,60245.017259,162.336676,5.324734,6.0,3.300685,Chennai,Enterprise,Female,0,0.0,16/10/2024,Google Ads,ok
425,CUST-01801,37.523525,46146.680410,181.226520,8.594339,4.0,4.300846,Hyderabad,Consumer,Male,0,1.0,2026-01-09,NaN,NaN
446,CUST-00987,NaN,61752.054991,141.922797,1.261793,5.0,3.972464,Chennai,consumer,NaN,NaN,0.0,NaN,WEB,ok
664,CUST-01030,50.546387,63908.913970,252.000000,8.117570,6.0,3.285228,Pune,Consumer,Female,1,0.0,15/11/2023,email,good customer
705,CUST-01502,30.504759,113807.443365,218.521526,NaN,6.0,2.636857,Mumbai,Consumer,Male,1,0.0,NaN,WEB,NaN
734,CUST-01113,24.173014,133770.215532,362.424198,8.951136,NaN,4.442666,Bengaluru,Consumer,Male,0,0.0,2024-02-08,Unknown,NaN
793,CUST-01074,18.886469,NaN,211.984092,7.659285,4.0,1.864035,Bengaluru,consumer,NaN,0,1.0,2023-12-30,Social,good
877,CUST-00391,18.000000,18706.444798,215.344839,2.037746,5.0,3.816982,Bengaluru,Consumer,Female,0,0.0,02/02/2022,Unknown,normal
904,CUST-00042,44.517851,79071.602736,389.270475,4.937681,6.0,3.088669,Bengaluru,Consumer,Female,1,1.0,11/02/2021,Social,normal
922,CUST-00779,38.724631,71048.050165,406.124323,5.134282,5.0,3.743458,Chennai,SMB,NaN,1,0.0,2023-03-04,Email,ok
942,CUST-00817,33.176089,NaN,240.729898,4.309966,7.0,4.207381,NaN,Consumer,Female,0,0.0,NaN,Email,NaN
1024,CUST-01134,NaN,39030.828372,195.707600,5.457041,7.0,4.630168,Hyderabad,UNKNOWN,Male,0,0.0,not_a_date,Unknown,NaN
1027,CUST-00843,59.044292,NaN,151.039790,2.787811,NaN,3.348861,Kolkata,NaN,Female,1,0.0,2023-05-09,Social,???
1102,CUST-00604,30.468950,61554.432370,216.621015,6.897778,NaN,2.875284,Delhi,SMB,Male,1,1.0,2022-09-07,Website,good
1194,CUST-01299,24.110424,NaN,225.420626,2.787186,10.0,4.658253,Mumbai,consumer,Female,1,0.0,2024-08-15,Website,???
1263,CUST-00672,41.268437,121161.110765,393.470831,NaN,6.0,NaN,Bengaluru,Consumer,Female,0,0.0,2022-11-15,Referral,NaN
1425,CUST-01204,36.771240,100968.183170,356.305997,1.538795,7.0,4.985398,Mumbai,Enterprise,Male,0,0.0,2024-05-10,referral,good
1516,CUST-00575,40.278121,52829.149225,280.213170,6.226230,3.0,3.450965,NaN,NaN,Female,1,0.0,2022-08-08,NaN,NaN
1613,CUST-01399,44.906558,NaN,248.101304,NaN,5.0,3.550965,Chennai,Enterprise,Female,0,1.0,2024-11-25,email,normal
1630,CUST-00161,NaN,41284.491898,261.433939,7.089411,6.0,NaN,Hyderabad,Consumer,Male,0,0.0,2021-06-13,NaN,NaN
1665,CUST-00897,29.887792,NaN,179.409088,5.076947,6.0,3.159210,Hyderabad,NaN,Male,0,0.0,2023-07-03,website,ok
1830,CUST-00613,20.915187,39476.087677,332.371104,7.679105,3.0,2.977596,Mumbai,NaN,Male,1,0.0,2022-09-16,referral,normal

In [549]:
# 22.Detect suspicious values such as -999 and 99999 in tenure_years and
# satisfaction.
df["tenure_years"]==-999
df["tenure_years"]==99999

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: tenure_years, Length: 2000, dtype: bool

In [550]:
df["satisfaction"]==-999
df["satisfaction"]==99999

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: satisfaction, Length: 2000, dtype: bool

In [551]:
# 23.Replace invalid/suspicious numerical values with NaN.
df[["tenure_years",'satisfaction']].replace({-999:np.nan,99999:np.nan})

      tenure_years  satisfaction
0         5.274076      3.382150
1         5.632826           NaN
2              NaN      4.195157
3         2.029634           NaN
4         2.648626      3.117326
...            ...           ...
1995     14.007477      3.556073
1996      0.673289      2.963094
1997      2.026485      3.079259
1998      7.168156      3.579652
1999      9.720663      1.100520

[2000 rows x 2 columns]

In [552]:
# 24.Fill missing numerical values using the median of each numerical column.
df.select_dtypes(include=["int","float"])

,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,churn_flag
0,45.867417,28198.410334,660.562918,5.274076,5.0,3.382150,0.0
1,47.765164,61312.831291,838.000000,5.632826,9.0,NaN,0.0
2,NaN,44199.671239,613.132775,NaN,8.0,4.195157,0.0
3,62.723578,56259.909611,720.236986,2.029634,4.0,NaN,0.0
4,NaN,31238.641956,549.183252,2.648626,5.0,3.117326,0.0
...,...,...,...,...,...,...,...
1995,27.269512,79436.893353,633.974006,14.007477,NaN,3.556073,0.0
1996,41.091685,39912.379911,701.720106,0.673289,8.0,2.963094,1.0
1997,26.215767,24522.265446,647.799336,2.026485,12.0,3.079259,0.0
1998,NaN,84103.610558,521.000000,7.168156,5.0,3.579652,1.0
1999,59.256095,53723.873924,576.739073,9.720663,NaN,1.100520,0.0

In [553]:
# 24.Fill missing numerical values using the median of each numerical column.
df_med=df[["age","income_usd","credit_score","tenure_years","monthly_visits","satisfaction","churn_flag"]].median()
df[["age","income_usd","credit_score","tenure_years","monthly_visits","satisfaction","churn_flag"]]=df[["age","income_usd","credit_score","tenure_years","monthly_visits","satisfaction","churn_flag"]].fillna(df_med)
df[["age","income_usd","credit_score","tenure_years","monthly_visits","satisfaction","churn_flag"]]

,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,churn_flag
0,45.867417,28198.410334,660.562918,5.274076,5.0,3.382150,0.0
1,47.765164,61312.831291,838.000000,5.632826,9.0,3.743458,0.0
2,38.016078,44199.671239,613.132775,4.688777,8.0,4.195157,0.0
3,62.723578,56259.909611,720.236986,2.029634,4.0,3.743458,0.0
4,38.016078,31238.641956,549.183252,2.648626,5.0,3.117326,0.0
...,...,...,...,...,...,...,...
1995,27.269512,79436.893353,633.974006,14.007477,6.0,3.556073,0.0
1996,41.091685,39912.379911,701.720106,0.673289,8.0,2.963094,1.0
1997,26.215767,24522.265446,647.799336,2.026485,12.0,3.079259,0.0
1998,38.016078,84103.610558,521.000000,7.168156,5.0,3.579652,1.0
1999,59.256095,53723.873924,576.739073,9.720663,6.0,1.100520,0.0

In [554]:
# 25.Fill missing categorical values using the mode of each categorical column.
df_mean=df[["customer_id","city","customer_segment","gender","is_active","signup_date","lead_source","notes_text"]].mode()
df[["customer_id","city","customer_segment","gender","is_active","signup_date","lead_source","notes_text"]]=df[["customer_id","city","customer_segment","gender","is_active","signup_date","lead_source","notes_text"]].fillna(df_mean)
df[["customer_id","city","customer_segment","gender","is_active","signup_date","lead_source","notes_text"]]

,customer_id,city,customer_segment,gender,is_active,signup_date,lead_source,notes_text
0,CUST-01861,Pune,consumer,Male,1,2026-03-11,Referral,normal
1,CUST-00354,Hyderabad,Consumer,Male,1,NaN,website,follow-up needed
2,CUST-01334,Mumbai,Consumer,Male,1,2024-09-20,Email,NaN
3,CUST-00906,Chennai,Enterprise,Male,0,2023-07-12,Website,normal
4,CUST-01290,Mumbai,Enterprise,Male,1,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...
1995,CUST-01131,Bengaluru,Consumer,Male,0,2024-02-26,email,normal
1996,CUST-01295,Pune,SMB,Male,0,2024-08-11,Website,good
1997,CUST-00861,Hyderabad,SMB.,Female,1,2023-05-27,WEB,???
1998,CUST-01460,Hyderabad,SMB,NaN,0,2025-01-26,Email,ok
1999,CUST-01127,Pune,Consumer,NaN,1,2024-02-22,???,good

In [555]:
# 26.Clean the signup_date column, which contains multiple date formats and
# invalid dates, and convert it to Pandas datetime.
df["signup_date"]=pd.to_datetime(df["signup_date"],format="mixed",errors="coerce")
df["signup_date"]

0      2026-03-11
1             NaT
2      2024-09-20
3      2023-07-12
4      2024-08-06
          ...
1995   2024-02-26
1996   2024-08-11
1997   2023-05-27
1998   2025-01-26
1999   2024-02-22
Name: signup_date, Length: 2000, dtype: datetime64[ns]

In [556]:
# 27.Find rows where signup_date could not be converted into a valid date.
df["signup_date"].isna()

0       False
1        True
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: signup_date, Length: 2000, dtype: bool

In [557]:
# 28.Clean the lead_source column by standardizing values such as Website,
# website, WEB, Referral, referral , Google Ads, and google_ads.
df["lead_source"]=df["lead_source"].replace({"website":"Website","WEB":"Website","referral":"Referral","google_ads":"Google Ads","email":"Email"})
df["lead_source"]

0       Referral
1        Website
2          Email
3        Website
4            NaN
          ...
1995       Email
1996     Website
1997     Website
1998       Email
1999         ???
Name: lead_source, Length: 2000, dtype: object

In [558]:
# 29.Create a final cleaned DataFrame containing:
# • cleaned column names
# • no duplicate IDs
# • standardized categorical values
# • numeric columns converted to numeric types
# • invalid values converted to NaN
# • missing values handled
# • detected outliers handled
df.drop_duplicates(inplace=True)
df.dtypes

customer_id                 object
age                        float64
income_usd                 float64
credit_score               float64
tenure_years               float64
monthly_visits             float64
satisfaction               float64
city                        object
customer_segment            object
gender                      object
is_active                   object
churn_flag                 float64
signup_date         datetime64[ns]
lead_source                 object
notes_text                  object
dtype: object

In [559]:
# 30.Perform a final data-quality audit using Pandas and NumPy:
# • Check remaining missing values
# • Check duplicate rows
# • Check duplicate customer IDs
# • Check data types
# • Check numerical ranges
# • Check unique categorical values
# • Confirm the final dataset is ready for analysis/ML
df.isnull().sum()

customer_id           0
age                   0
income_usd            0
credit_score          0
tenure_years          0
monthly_visits        0
satisfaction          0
city                300
customer_segment    380
gender              239
is_active           339
churn_flag            0
signup_date         271
lead_source         420
notes_text          655
dtype: int64

In [560]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [602]:

df["customer_id"].drop_duplicates(inplace=True)
df["customer_id"].duplicated().sum()

20

In [604]:
df.dtypes

customer_id                 object
age                        float64
income_usd                 float64
credit_score               float64
tenure_years               float64
monthly_visits             float64
satisfaction               float64
city                        object
customer_segment            object
gender                      object
is_active                   object
churn_flag                 float64
signup_date         datetime64[ns]
lead_source                 object
notes_text                  object
dtype: object

In [614]:
df.nunique()

customer_id         1980
age                 1352
income_usd          1355
credit_score        1569
tenure_years        1733
monthly_visits        25
satisfaction        1468
city                   7
customer_segment       6
gender                 2
is_active              4
churn_flag             2
signup_date         1693
lead_source            8
notes_text            10
dtype: int64

In [616]:
df.to_csv("Cleaned_customer_data.csv")