#### EV Resale Price Regression

In [511]:
# 1. Data Quality Audit
# Perform a complete audit of the dataset:
# • shape
# • datatypes
# • missing values
# • duplicate records
# • unique vehicle IDs
# • categorical distributions
# Identify every data-quality problem before modifying the dataset.
import pandas as pd
df=pd.read_csv("C:\\Users\\vaish\\Downloads\\EV_Resale_Price_Regression.csv")

In [512]:
print(df.shape)
print()
print(df.dtypes)
print()
print(df.isnull().sum())
print()
print(df.duplicated().sum())
print()
print(df.nunique())
print()
print(df.select_dtypes(include=["int"]).columns)
print(df.value_counts().sum())

(1000, 15)

vehicle_id               object
listing_date             object
manufacture_year          int64
brand                    object
vehicle_type             object
battery_capacity_kwh    float64
battery_health_pct      float64
range_km                float64
km_driven               float64
charging_time_hr        float64
fast_charging            object
owner_count               int64
city                     object
service_history          object
resale_price            float64
dtype: object

vehicle_id               0
listing_date             0
manufacture_year         0
brand                    0
vehicle_type             0
battery_capacity_kwh    25
battery_health_pct      30
range_km                20
km_driven                0
charging_time_hr        24
fast_charging            0
owner_count              0
city                     0
service_history         30
resale_price             0
dtype: int64

0

vehicle_id               994
listing_date            1000
manufacture_year          10
brand                      5
vehicle_type               4
battery_capacity_kwh     459
battery_health_pct       197
range_km                 341
km_driven                980
charging_time_hr          87
fast_charging              2
owner_count                4
city                       6
service_history            3
resale_price             994
dtype: int64

Index(['manufacture_year', 'owner_count'], dtype='object')
876

In [513]:
# 2. Duplicate Vehicle Investigation
# vehicle_id is expected to uniquely identify a vehicle.
# Determine:
# • how many duplicated vehicle_id values exist
# • which vehicle IDs are duplicated
# • how many records are affected
# Then decide how you would handle these records without blindly using drop_duplicates().
df["vehicle_id"].duplicated().sum()

6

In [514]:
df["vehicle_id"].duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: vehicle_id, Length: 1000, dtype: bool

In [515]:
df.sort_values("vehicle_id")

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
922,EV-20000,2027-07-12,2018,Nexora,SUV,62.6,87.5,474.0,137443.0,5.6,No,3,Pune,Complete,1440997.0
372,EV-20001,2026-01-08,2018,E-Motion,SUV,52.4,100.0,473.0,27643.0,NaN,Yes,2,Delhi,Partial,1830937.0
666,EV-20002,2026-10-29,2022,Atheron,Hatchback,69.7,92.0,363.0,75343.0,7.6,No,1,Pune,Complete,1616533.0
313,EV-20003,2025-11-10,2017,Atheron,Hatchback,62.6,97.2,290.0,77298.0,4.5,Yes,1,Bengaluru,Complete,1479957.0
32,EV-20004,2025-02-02,2019,E-Motion,Sedan,53.7,NaN,343.0,41146.0,5.5,Yes,2,Delhi,Complete,1523378.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,EV-20995,2026-09-12,2018,GreenDrive,Hatchback,68.4,100.0,400.0,115179.0,7.8,Yes,1,Delhi,Partial,1547603.0
755,EV-20996,2027-01-26,2020,Nexora,SUV,64.0,94.6,387.0,70303.0,6.7,No,2,Bengaluru,Complete,1647002.0
28,EV-20997,2025-01-29,2023,Voltix,Sedan,54.6,96.9,358.0,104549.0,5.6,No,1,Delhi,Complete,1486145.0
582,EV-20998,2026-08-06,2025,Atheron,Sedan,45.7,93.6,274.0,52948.0,6.2,Yes,4,Mumbai,NaN,1517539.0
733,EV-20999,2027-01-04,2021,Nexora,Crossover,50.2,93.5,184.0,53473.0,8.5,Yes,2,Mumbai,Complete,1613808.0

In [516]:
# 3. Date Conversion & Validation
# Convert listing_date into a proper datetime column.
# Then investigate:
# • earliest listing date
# • latest listing date
# • invalid/missing dates
# • whether the date column is suitable for feature engineering.
df["listing_date"]=pd.to_datetime(df["listing_date"])
df

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.000000,10.0,No,1,Chennai,Complete,1527836.0
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.844779,7.1,No,2,Chennai,Complete,2040760.0
2,EV-20654,2025-01-03,2019,Nexora,Crossover,53.9,91.2,NaN,12003.000000,3.6,Yes,1,Chennai,Complete,1830249.0
3,EV-20935,2025-01-04,2022,GreenDrive,Hatchback,60.1,89.3,528.0,13623.000000,7.8,Yes,2,Delhi,Complete,1726422.0
4,EV-20827,2025-01-05,2024,GreenDrive,Sedan,53.0,92.0,264.0,28548.000000,6.1,No,1,Pune,Complete,1642232.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,EV-20357,2027-09-23,2017,E-Motion,Sedan,37.9,89.9,333.0,61861.000000,3.0,No,1,Bengaluru,Complete,1338124.0
996,EV-20756,2027-09-24,2020,Atheron,Hatchback,67.5,99.9,290.0,55605.000000,9.2,Yes,1,Bengaluru,Complete,1624596.0
997,EV-20984,2027-09-25,2025,Atheron,Crossover,91.1,81.8,434.0,23708.000000,2.0,No,1,Delhi,Partial,1958519.0
998,EV-20410,2027-09-26,2019,GreenDrive,Sedan,76.8,98.6,264.0,39435.000000,2.8,Yes,1,Chennai,Complete,1724555.0
999,EV-20168,2027-09-27,2019,Voltix,Crossover,63.6,88.2,150.0,103173.000000,NaN,No,3,Pune,Complete,1232571.0

In [517]:
df["listing_date"].sort_values()
df.head(1)

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0,10.0,No,1,Chennai,Complete,1527836.0

In [518]:
df["listing_date"].sort_values()
df.tail(1)

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
999,EV-20168,2027-09-27,2019,Voltix,Crossover,63.6,88.2,150.0,103173.0,NaN,No,3,Pune,Complete,1232571.0

In [519]:
df["listing_date"].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: listing_date, Length: 1000, dtype: bool

In [520]:
# 4. Vehicle Age Feature
# Create vehicle_age using:
# listing year − manufacture year
# Then identify whether any vehicle has:
# • age < 0
# • age = 0
# • unusually high age
df["manufacture_year"]=pd.to_numeric(df["manufacture_year"])
df["vehicle_age"]=df["listing_date"].dt.year - df["manufacture_year"]
df["vehicle_age"]

0       4
1       0
2       6
3       3
4       1
       ..
995    10
996     7
997     2
998     8
999     8
Name: vehicle_age, Length: 1000, dtype: int64

In [521]:
print(df["vehicle_age"]<0)

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: vehicle_age, Length: 1000, dtype: bool

In [522]:
print(df["vehicle_age"]==0)

0      False
1       True
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: vehicle_age, Length: 1000, dtype: bool

In [523]:
print(df["vehicle_age"]>30)

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: vehicle_age, Length: 1000, dtype: bool

In [524]:

# 5. Battery Data Imputation
# The following columns contain missing values:
# battery_capacity_kwh, battery_health_pct, range_km, charging_time_hr
# Develop an appropriate missing-value strategy for each column.
# Do not automatically use the same statistic for every column.
# Explain why you selected mean, median, or another strategy.
bat_mean=df["battery_capacity_kwh"].median()
df["battery_capacity_kwh"]=df["battery_capacity_kwh"].fillna(bat_mean)
df["battery_capacity_kwh"]

0      46.9
1      80.6
2      53.9
3      60.1
4      53.0
       ...
995    37.9
996    67.5
997    91.1
998    76.8
999    63.6
Name: battery_capacity_kwh, Length: 1000, dtype: float64

In [525]:
health_mean=df["battery_health_pct"].mean()
df["battery_health_pct"]=df["battery_health_pct"].fillna(health_mean)
df["battery_health_pct"]

0      89.6
1      99.5
2      91.2
3      89.3
4      92.0
       ...
995    89.9
996    99.9
997    81.8
998    98.6
999    88.2
Name: battery_health_pct, Length: 1000, dtype: float64

In [526]:
ragne_med=df["range_km"].median()
df["range_km"]=df["range_km"].fillna(ragne_med)
df["range_km"]

0      313.0
1      543.0
2      371.0
3      528.0
4      264.0
       ...
995    333.0
996    290.0
997    434.0
998    264.0
999    150.0
Name: range_km, Length: 1000, dtype: float64

In [527]:
char_med=df["charging_time_hr"].median()
df["charging_time_hr"]=df["charging_time_hr"].fillna(char_med)
df["charging_time_hr"]

0      10.00
1       7.10
2       3.60
3       7.80
4       6.10
       ...
995     3.00
996     9.20
997     2.00
998     2.80
999     6.25
Name: charging_time_hr, Length: 1000, dtype: float64

In [528]:
# 6. Battery Health Outlier Investigation
# Analyze battery_health_pct.
# Identify:
# • values below a reasonable minimum
# • values above 100
# • extreme observations
# Then decide whether to remove, cap, or retain suspicious values.
df["battery_health_pct"]<0

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: battery_health_pct, Length: 1000, dtype: bool

In [529]:
df["battery_health_pct"]>100

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: battery_health_pct, Length: 1000, dtype: bool

In [530]:
df["battery_health_pct"]>99

0      False
1       True
2      False
3      False
4      False
       ...
995    False
996     True
997    False
998    False
999    False
Name: battery_health_pct, Length: 1000, dtype: bool

In [531]:
# 7. Range vs Battery Capacity
# Create range_per_kwh using:
# range_km / battery_capacity_kwh
# Identify vehicles with unusually low or high efficiency.
df["range_per_kwh"]=df["range_km"]/df['battery_capacity_kwh']
df["range_per_kwh"]

0      6.673774
1      6.736973
2      6.883117
3      8.785358
4      4.981132
         ...
995    8.786280
996    4.296296
997    4.763996
998    3.437500
999    2.358491
Name: range_per_kwh, Length: 1000, dtype: float64

In [532]:
low=df["range_per_kwh"]<=3
low

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999     True
Name: range_per_kwh, Length: 1000, dtype: bool

In [533]:
high=df["range_per_kwh"]>=8
high

0      False
1      False
2      False
3       True
4      False
       ...
995     True
996    False
997    False
998    False
999    False
Name: range_per_kwh, Length: 1000, dtype: bool

In [534]:
# 8. Driving Intensity Feature
# Create km_per_year using:
# km_driven / vehicle_age
# Handle the special case where vehicle_age = 0.
# Identify unusually high annual driving.
df["km_per_year"]=df["km_driven"]/df["vehicle_age"]
df["km_per_year"]

0      7.113500e+03
1               inf
2      2.000500e+03
3      4.541000e+03
4      2.854800e+04
           ...
995    6.186100e+03
996    7.943571e+03
997    1.185400e+04
998    4.929375e+03
999    1.289662e+04
Name: km_per_year, Length: 1000, dtype: float64

In [535]:
high=df["km_per_year"]>23457653
high

0      False
1       True
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: km_per_year, Length: 1000, dtype: bool

In [536]:
special=df["km_per_year"]==0
special

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: km_per_year, Length: 1000, dtype: bool

In [537]:
# 9. Charging Efficiency
# Create charging_efficiency using:
# range_km / charging_time_hr
# Investigate missing values and extreme values before using this feature in a regression model.
df["charging_efficiency"]=df["range_km"]/df["charging_time_hr"]
df["charging_efficiency"]

0       31.300000
1       76.478873
2      103.055556
3       67.692308
4       43.278689
          ...
995    111.000000
996     31.521739
997    217.000000
998     94.285714
999     24.000000
Name: charging_efficiency, Length: 1000, dtype: float64

In [538]:
df["charging_efficiency"].isnull().sum()

0

In [539]:
# 10. Ownership Analysis
# Analyze owner_count.
# Determine:
# • frequency of each ownership level
# • whether any values are invalid
# • whether owner count should be treated as numerical or categorical for regression.
df["owner_count"].value_counts().sort_index()

owner_count
1    532
2    302
3    126
4     40
Name: count, dtype: int64

In [540]:
df["owner_count"].value_counts().sort_index()*100

owner_count
1    53200
2    30200
3    12600
4     4000
Name: count, dtype: int64

In [541]:
df["owner_count"].isnull().sum()

0

In [542]:
df["owner_count"]=pd.to_numeric(df["owner_count"], errors="coerce")
df["owner_status"]=["Invalid" if count<1 else "valid" for count in df["owner_count"] ]
df["owner_status"]
df[["owner_count", "owner_status"]].head()

   owner_count owner_status
0            1        valid
1            2        valid
2            1        valid
3            2        valid
4            1        valid

In [543]:
df["owner_count"].describe()

count    1000.000000
mean        1.674000
std         0.844059
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         4.000000
Name: owner_count, dtype: float64

In [544]:
# 11. Categorical Data Audit
# Analyze: brand, vehicle_type, fast_charging, city, .service_history.
# For each column:
# • count unique categories
# • inspect frequencies
# • identify missing values
# • identify suspicious/inconsistent categories.
col=["brand","vehicle_type","fast_charging","city","service_history"]
for i in col:
    i=df[col].nunique().sum()
    print(i)

20
20
20
20
20

In [545]:
for i in col:
    i=df[col].isnull().sum()
    print(i)

brand               0
vehicle_type        0
fast_charging       0
city                0
service_history    30
dtype: int64
brand               0
vehicle_type        0
fast_charging       0
city                0
service_history    30
dtype: int64
brand               0
vehicle_type        0
fast_charging       0
city                0
service_history    30
dtype: int64
brand               0
vehicle_type        0
fast_charging       0
city                0
service_history    30
dtype: int64
brand               0
vehicle_type        0
fast_charging       0
city                0
service_history    30
dtype: int64

In [546]:
for i in col:
    i=df[col].value_counts().sum()
    print(i)

970
970
970
970
970

In [559]:
obj_cols = df.select_dtypes(include="object").columns
for i in col:
    df[i]=df[i].astype(str).str.strip().str.title()
    print(i)

brand
vehicle_type
fast_charging
city
service_history

In [567]:
# 12. Service History Cleaning
# service_history contains Complete, Partial, Missing, and NaN.
# Determine whether “Missing” and actual NaN represent the same business meaning.
# Then create a consistent representation suitable for ML.
import numpy as np
df["service_history"].nunique()

4

In [569]:
df["service_history"].value_counts()

service_history
Complete    590
Partial     297
Missing      83
Nan          30
Name: count, dtype: int64

In [585]:
df["service_history"]=df["service_history"].replace("Nan",np.nan).fillna("Unknown")
df["service_history"]

0      Complete
1      Complete
2      Complete
3      Complete
4      Complete
         ...
995    Complete
996    Complete
997     Partial
998    Complete
999    Complete
Name: service_history, Length: 1000, dtype: object

In [587]:
df["service_history"].value_counts()

service_history
Complete    590
Partial     297
Unknown     113
Name: count, dtype: int64

In [589]:
# 13. Fast Charging Transformation
# Transform fast_charging from Yes / No into a binary numerical representation.
# Verify the transformation using frequency counts before and after.
df["fast_charging"]=df["fast_charging"].replace({"Yes":1,"No":0})

C:\Users\vaish\AppData\Local\Temp\ipykernel_28204\382159371.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["fast_charging"]=df["fast_charging"].replace({"Yes":1,"No":0})

In [591]:
df["fast_charging"]

0      0
1      0
2      1
3      1
4      0
      ..
995    0
996    1
997    0
998    1
999    0
Name: fast_charging, Length: 1000, dtype: int64

In [ ]:
# 14. Target Analysis
# Analyze resale_price.
# Calculate and inspect:
# • mean
# • median
# • minimum
# • maximum
# • standard deviation
# • potential extreme values
# Determine whether the target contains suspicious observations that could strongly influence a regression model.
sale_mean=df["resale_price"].mean()
df["resale_price"]=df["resale_price"].fillna(sale_mean)
df["resale_price"]

In [ ]:
sale_med=df["resale_price"].median()
df["resale_price"]=df["resale_price"].fillna(sale_med)
df["resale_price"]

In [ ]:
sale_min=df["resale_price"].min()
df["resale_price"]=df["resale_price"].fillna(sale_min)
df["resale_price"]

In [ ]:
sale_max=df["resale_price"].max()
df["resale_price"]=df["resale_price"].fillna(sale_max)
df["resale_price"]

In [595]:
# 15. Price-per-Kilometer Feature
# Create price_per_km using:
# resale_price / km_driven
# Investigate whether extremely low/high values are caused by very low mileage, very high price, or data-quality
# problems.
df["price_per_km"]=df["resale_price"]/df["km_driven"]
df["price_per_km"]

0       53.694946
1       11.094955
2      152.482629
3      126.728474
4       57.525291
          ...
995     21.631141
996     29.216725
997     82.610047
998     43.731584
999     11.946643
Name: price_per_km, Length: 1000, dtype: float64

In [597]:
df["price_per_km"].describe()

count    1000.000000
mean       47.898997
std        38.160068
min         5.618022
25%        22.713155
50%        37.871836
75%        61.903746
max       296.870220
Name: price_per_km, dtype: float64

In [599]:
# 16. Battery Health × Usage Feature
# Create a combined feature called battery_usage_index based on battery_health_pct and km_driven.
# Design a meaningful formula and explain why this feature could help predict resale price.
df["battery_usage_index"]=df["battery_health_pct"]/(df["km_driven"]+1)
df["battery_usage_index"]

0      0.003149
1      0.000541
2      0.007597
3      0.006555
4      0.003223
         ...
995    0.001453
996    0.001797
997    0.003450
998    0.002500
999    0.000855
Name: battery_usage_index, Length: 1000, dtype: float64

In [624]:
# 17. Complete Missing-Value Pipeline
# Build a cleaning pipeline for all columns containing missing values:
# battery_capacity_kwh, battery_health_pct, range_km, charging_time_hr, service_history
# Requirements:
# • numeric missing values → appropriate statistical treatment
# • categorical missing values → appropriate category treatment
# • verify zero unintended missing values afterward
# • preserve the original dataset in a separate DataFrame.
colum=["battery_capacity_kwh","battery_health_pct","range_km","charging_time_hr","service_history"]
for i in colum:
    i=df[i].isnull().sum()
    print(i)

0
0
0
0
0

In [626]:
for i in colum:
    i=df[i].astype("int")
    print(i)

0      46
1      80
2      53
3      60
4      53
       ..
995    37
996    67
997    91
998    76
999    63
Name: battery_capacity_kwh, Length: 1000, dtype: int32
0      89
1      99
2      91
3      89
4      92
       ..
995    89
996    99
997    81
998    98
999    88
Name: battery_health_pct, Length: 1000, dtype: int32
0      313
1      543
2      371
3      528
4      264
      ...
995    333
996    290
997    434
998    264
999    150
Name: range_km, Length: 1000, dtype: int32
0      10
1       7
2       3
3       7
4       6
       ..
995     3
996     9
997     2
998     2
999     6
Name: charging_time_hr, Length: 1000, dtype: int32

ValueError: invalid literal for int() with base 10: 'Complete'

In [603]:
# 18. Regression Feature Preparation
# Prepare the dataset for a regression model.
# Separate:
# X = features
# y = resale_price
# Remove columns that should not directly be used as model features, such as identifiers.
# Classify every remaining feature as numerical, categorical, or date-derived.
X=df[['vehicle_id', 'listing_date', 'manufacture_year', 'brand',
       'vehicle_type', 'battery_capacity_kwh', 'battery_health_pct',
       'range_km', 'km_driven', 'charging_time_hr', 'fast_charging',
       'owner_count', 'city', 'service_history', 'vehicle_age',
       'range_per_kwh', 'km_per_year', 'charging_efficiency', 'owner_status',
       'price_per_km', 'battery_usage_index']]
y=df["resale_price"]

In [610]:

df.drop("vehicle_id",axis=1,inplace=True)

In [612]:
numerical=df.select_dtypes(include=["int","float"])

,manufacture_year,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,resale_price,vehicle_age,range_per_kwh,km_per_year,charging_efficiency,price_per_km,battery_usage_index
0,2021,46.9,89.6,313.0,28454.000000,10.00,0,1,1527836.0,4,6.673774,7.113500e+03,31.300000,53.694946,0.003149
1,2025,80.6,99.5,543.0,183935.844779,7.10,0,2,2040760.0,0,6.736973,inf,76.478873,11.094955,0.000541
2,2019,53.9,91.2,371.0,12003.000000,3.60,1,1,1830249.0,6,6.883117,2.000500e+03,103.055556,152.482629,0.007597
3,2022,60.1,89.3,528.0,13623.000000,7.80,1,2,1726422.0,3,8.785358,4.541000e+03,67.692308,126.728474,0.006555
4,2024,53.0,92.0,264.0,28548.000000,6.10,0,1,1642232.0,1,4.981132,2.854800e+04,43.278689,57.525291,0.003223
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2017,37.9,89.9,333.0,61861.000000,3.00,0,1,1338124.0,10,8.786280,6.186100e+03,111.000000,21.631141,0.001453
996,2020,67.5,99.9,290.0,55605.000000,9.20,1,1,1624596.0,7,4.296296,7.943571e+03,31.521739,29.216725,0.001797
997,2025,91.1,81.8,434.0,23708.000000,2.00,0,1,1958519.0,2,4.763996,1.185400e+04,217.000000,82.610047,0.003450
998,2019,76.8,98.6,264.0,39435.000000,2.80,1,1,1724555.0,8,3.437500,4.929375e+03,94.285714,43.731584,0.002500
999,2019,63.6,88.2,150.0,103173.000000,6.25,0,3,1232571.0,8,2.358491,1.289662e+04,24.000000,11.946643,0.000855

In [618]:
categorial=df.select_dtypes(include="object")
categorial

          brand vehicle_type       city service_history owner_status
0        Nexora          Suv    Chennai        Complete        valid
1        Nexora    Crossover    Chennai        Complete        valid
2        Nexora    Crossover    Chennai        Complete        valid
3    Greendrive    Hatchback      Delhi        Complete        valid
4    Greendrive        Sedan       Pune        Complete        valid
..          ...          ...        ...             ...          ...
995    E-Motion        Sedan  Bengaluru        Complete        valid
996     Atheron    Hatchback  Bengaluru        Complete        valid
997     Atheron    Crossover      Delhi         Partial        valid
998  Greendrive        Sedan    Chennai        Complete        valid
999      Voltix    Crossover       Pune        Complete        valid

[1000 rows x 5 columns]

In [622]:
datetime=df.select_dtypes(include="datetime")
datetime

    listing_date
0     2025-01-01
1     2025-01-02
2     2025-01-03
3     2025-01-04
4     2025-01-05
..           ...
995   2027-09-23
996   2027-09-24
997   2027-09-25
998   2027-09-26
999   2027-09-27

[1000 rows x 1 columns]

In [ ]:
# 19. Leakage Investigation
# Before training the regression model, inspect every engineered feature and determine whether it could cause
# target leakage.
# Evaluate whether features derived from resale_price should be allowed inside X.
# Identify all problematic features and remove them.

In [ ]:
# 20. Ultimate Hard Problem — Production-Ready EV Dataset
# You are given this raw EV resale dataset by a machine-learning team.
# Build a clean modeling dataset following this workflow:
# Step 1 — Audit: shape, info, missing values, duplicates, categorical distributions.
# Step 2 — Clean identifiers: investigate duplicated vehicle_id values and determine an appropriate treatment.
# Step 3 — Clean dates: convert listing_date and derive listing_year, listing_month, listing_quarter.
# Step 4 — Clean numerical features: handle missing and suspicious values in battery_capacity_kwh,
# battery_health_pct, range_km, km_driven, charging_time_hr, owner_count.
# Step 5 — Clean categorical features: clean brand, vehicle_type, fast_charging, city, service_history.
# Step 6 — Feature engineering: create vehicle_age, range_per_kwh, km_per_year, charging_efficiency,
# battery_usage_index.
# Step 7 — Leakage check: make sure no feature contains information derived from resale_price.
# Step 8 — Final validation: no unintended duplicate vehicles, no invalid dates, no unexplained missing values,
# correct numerical datatypes, consistent categorical values, no impossible vehicle ages, no impossible
# battery-health values, and no target leakage.
# Step 9 — Final output: produce X (cleaned independent variables) and y (resale_price).
# Do not train a model. The task is to prepare a high-quality regression dataset ready for modeling.
df1=pd.read_csv("C:\\Users\\vaish\\Downloads\\EV_Resale_Price_Regression.csv")

In [ ]:
df1.shape

In [ ]:
df1.info()

In [ ]:
df1.isnull().sum()

In [ ]:
df1.duplicated().sum()

In [ ]:
df1.dtypes

In [ ]:
col=df1.select_dtypes(include="object")
for i in col:
    print(df[i].value_counts(dropna=False))

In [ ]:
# Step 2 — Clean identifiers: investigate duplicated vehicle_id values and determine an appropriate treatment.
df1.drop_duplicates()

In [ ]:
# Step 3 — Clean dates: convert listing_date and derive listing_year, listing_month, listing_quarter.
df1["listing_date"]=pd.to_datetime(df1["listing_date"],format ="%Y-%m-%d")
df1["listing_year"]=df1["listing_date"].dt.year
df1["listing_month"]=df1["listing_date"].dt.month
df1["listing_quarter"]=df1["listing_date"].dt.day
df1

In [ ]:
# Step 4 — Clean numerical features: handle missing and suspicious values in battery_capacity_kwh,
#battery_health_pct, range_km, km_driven, charging_time_hr, owner_count .
columns=["battery_capacity_kwh","battery_health_pct","range_km","km_driven","charging_time_hr","owner_count"]
for col in columns:
    df1[col]=pd.to_numeric(df1[col],errors="coerce")
    df1[col]=df1[col].fillna(df1[col].median())

In [ ]:
df1["service_history"]=df1["service_history"].fillna(method="ffill")
df1["service_history"]

In [ ]:
for i in columns:
    i=df1[col].isnull().sum()
    print(i)

In [ ]:
# Step 5 — Clean categorical features: clean brand, vehicle_type, fast_charging, city, service_history.
caterory=["brand","vehicle_type","fast_charging","city","service_history"]
for i in caterory:
    i=df1[col].astype(str).str.strip().str.title()
    print(i)

In [ ]:
for i in caterory:
    df1[col]=df1[col].drop_duplicates()
    print(df1[col])

In [ ]:
for i in caterory:
    i=df1[col].duplicated().sum()
    print(i)

In [ ]:
df1

In [ ]:
# Step 6 — Feature engineering: create vehicle_age, range_per_kwh, km_per_year, charging_efficiency,
# battery_usage_index.

In [ ]:
# Step 7 — Leakage check: make sure no feature contains information derived from resale_price.