In [647]:
import pandas as pd
df=pd.read_csv("C:\\Users\\vaish\\Downloads\\customer_analytics.csv")
df1=pd.read_csv("C:\\Users\\vaish\\Downloads\\customer_analytics.csv")

#### Exam Task on Pandas Method (Data Cleaning)

In [606]:
# Part 1 — Inspect & Understand the Dataset
# Q1. Load the dataset
# Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
# Then display the first 10 rows.
# Use: pd.read_csv(), head()
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68.0,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47.0,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65.0,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63.0,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42.0,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

In [607]:
# Q2. Inspect the end of the dataset
# Display the last 15 rows.
# Use: tail()
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51.0,214004.0,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573.0,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54.0,123511.0,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31.0,125500.0,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619.0,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41.0,201611.0,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61.0,128850.0,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33.0,88037.0,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43.0,122756.0,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18.0,189232.0,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [608]:
# Q3. Random inspection
# Display 10 random records.
# Use: sample()
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
650,101037,64.0,124853.0,213970.76,812,6,Delhi,Retail,Mobile,2022-12-13 00:00:00,Yes,Low,20523.56,118,4.4
761,100775,54.0,213856.0,169097.99,429,9,NaN,Corporate,Mobile,2025-04-23 00:00:00,NaN,High,673.79,78,NaN
1553,101116,abc,NaN,91209.08,384,13,Kolkata,SME,Branch,2022-05-10 00:00:00,Yes,High,8631.05,9,8.1
40,101264,34.0,204761.0,262621.69,432,8,Chennai,Retail,Branch,2021-11-18 00:00:00,No,High,2794.49,38,7.9
1754,101734,57.0,243561.0,196915.76,680,5,Kolkata,Corporate,Mobile,2025-05-30 00:00:00,0,Medium,48016.86,75,4.8
584,100782,39.0,119018.0,52224.5,638,9,Hyderabad,Premium,Agent,2022-02-03 00:00:00,Yes,Medium,21316.62,66,2.7
600,100030,29.0,abc,89018.29,389,3,Chennai,SME,Mobile,2024-12-07 00:00:00,Yes,High,24646.77,64,1.0
1763,101795,33.0,197886.0,210414.99,430,13,Chennai,Retail,Online,2022-11-03 00:00:00,NO,High,17223.77,148,3.8
1861,100767,missing,117578.0,129112.42,756,4,bangalore,SME,Mobile,2022-02-12 00:00:00,No,Low,27233.25,53,5.9
1738,101535,18.0,213786.0,169706.45,613,9,Hyderabad,SME,Online,2024-04-23 00:00:00,no,Medium,11515.22,56,7.1

In [609]:
# Q4. Dataset audit
# Use info() to identify:
# • Number of rows
# • Number of columns
# • Columns with missing values
# • Columns having incorrect/object datatypes
# Use: info()\
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [610]:
# # Q5. Missing-value audit
# # Calculate the number of missing values in every column.
# # Then verify the result using both:
# # isnull()
# and
# isna()
df.isnull().sum()
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

#### Part 2 — Detect & Fix Data Quality Problems

In [612]:
# Q6. Duplicate investigation
# Find how many duplicate rows exist.
# Do not remove them yet.
# Use: duplicated()
df.duplicated().sum()

40

In [613]:
# Q7. Remove duplicates
# Remove all duplicate records and store the cleaned result back into df.
# Then verify that duplicates no longer exist.
# Use: drop_duplicates(), duplicated()
df.drop_duplicates(inplace=True)
print(df.duplicated().sum())

0

In [614]:
# Q8. Numeric column investigation
# Select only numeric columns.
# Identify which columns are currently numeric and which potentially numeric columns have
# become object because of invalid values.
# Use: select_dtypes()
select_num=df.select_dtypes(include=["int","float"])
select_num

      Customer_ID  Tenure_Years  Satisfaction_Score
0          101317             3                 3.1
1          101001             8                 8.2
2          101069            12                 6.3
3          101968            14                 9.7
4          100530             4                 3.7
...           ...           ...                 ...
2035       101131            12                 8.6
2036       101295             8                 2.6
2037       100861             8                 1.3
2038       101460             8                 9.3
2039       101127             6                 3.1

[2000 rows x 3 columns]

In [615]:
# Q9. Fix Age
# The Age column contains:
# • Valid numbers
# • Missing values
# • Invalid text such as unknown, N/A, etc.
# Convert Age into a proper numeric column.
# Invalid values should become missing values.
# Then fill missing Age values using the median age.
df["Age"]=pd.to_numeric(df["Age"],errors="coerce")
print(df["Age"])
age_med=df["Age"].median()
df["Age"]=df["Age"].fillna(age_med)
df["Age"]

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2000, dtype: float64

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2000, dtype: float64

In [616]:
# Q10. Fix Annual Income
# Clean Annual_Income.
# Requirements:
# 1. Convert invalid values to missing.
# 2. Convert the column to a numeric datatype.
# 3. Calculate the median.
# 4. Fill missing values using the median.
# Use: pd.to_numeric(), median(), fillna(), astype()
df["Annual_Income"]=df["Annual_Income"].fillna(method="ffill")
df["Annual_Income"]

C:\Users\vaish\AppData\Local\Temp\ipykernel_27164\3093852121.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Annual_Income"]=df["Annual_Income"].fillna(method="ffill")

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: Annual_Income, Length: 2000, dtype: object

In [921]:
df["Annual_Income"]=pd.to_numeric(df["Annual_Income"],errors="coerce")
df["Annual_Income"]
df["Annual_Income"]=df["Annual_Income"].astype("int")
df["Annual_Income"]

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
med_income=df["Annual_Income"].median()
print(med_income)
df["Annual_Income"]=df["Annual_Income"].fillna(med_income)
df["Annual_Income"]

#### Part 3 — Numerical Cleaning

In [ ]:
# Q11. Clean Account Balance
# The Account_Balance column contains invalid strings and missing values.
# Clean the column and replace missing values with the mean Account Balance.
# Use:
# • pd.to_numeric()
# • mean()
# • fillna()
df["Account_Balance"]=pd.to_numeric(df["Account_Balance"],errors="coerce")
df["Account_Balance"]

In [ ]:
mean_anu=df["Account_Balance"].mean()
mean_anu
df["Account_Balance"]=df["Account_Balance"].fillna(mean_anu)
df["Account_Balance"]

In [ ]:
# # Q12. Clean Credit Score
# # Clean Credit_Score.
# # Invalid values should become missing.
# # Then replace missing values with the median Credit Score.
# # Finally convert the column to integer.
# # Use:
# # • pd.to_numeric()
# # • median()
# • fillna()
# • astype()
df["Credit_Score"]=pd.to_numeric(df["Credit_Score"],errors="coerce")
df["Credit_Score"]

In [ ]:
anu_med=df["Credit_Score"].median
anu_med
df["Credit_Score"]=df["Credit_Score"].fillna(anu_med)
df["Credit_Score"]

In [ ]:
# Q13. Clean Monthly Spend
# Clean Monthly_Spend.
# Then:
# • Convert it to numeric.
# • Replace invalid values.
# • Replace missing values using the median.
# • Make sure the final column is numeric.
df["Monthly_Spend"]=pd.to_numeric(df["Monthly_Spend"],errors="coerce")
df["Monthly_Spend"]

In [ ]:
df["Monthly_Spend"]=df["Monthly_Spend"].fillna(method="ffill")
df["Monthly_Spend"]

In [ ]:
med_spend=df["Monthly_Spend"].median()
med_spend
df["Monthly_Spend"]=df["Monthly_Spend"].fillna(med_spend)
df["Monthly_Spend"]

In [ ]:
df["Monthly_Spend"].dtype

In [ ]:
# Q14. Clean Transactions
# The Transactions column contains invalid strings.
# Convert it to numeric and replace invalid values with the median number of transactions.
# Then convert the final column to integer.
df["Transactions"]=pd.to_numeric(df["Transactions"],errors="coerce")
df["Transactions"]

In [ ]:
med_trans=df["Transactions"].median()
med_trans
df["Transactions"]=df["Transactions"].fillna(med_trans)
df["Transactions"]

In [ ]:
df["Transactions"]=df["Transactions"].astype("int")
df["Transactions"]

In [ ]:
# Q15. Clean Satisfaction Score
# Clean Satisfaction_Score.
# Replace missing/invalid values using the mean Satisfaction Score.
# Then convert the column to float.
mean_score=df["Satisfaction_Score"].mean()
mean_score
df["Satisfaction_Score"]=df["Satisfaction_Score"].fillna(mean_score)
df["Satisfaction_Score"]

In [ ]:

df["Satisfaction_Score"]=df["Satisfaction_Score"].astype("float")
df["Satisfaction_Score"]

#### Part 4 — Date Cleaning

In [ ]:
# # Q16. Investigate Join_Date
# Inspect the Join_Date column.
# Identify the problems caused by:
# • Missing dates
# • Different date formats
# • Invalid date strings
# Do not clean it yet.
df["Join_Date"].isnull()

In [ ]:
df["Join_Date"]

In [ ]:
# Q17. Convert Join_Date
# Convert Join_Date into a proper Pandas datetime column.
# Any invalid dates should become missing values.
# Use: pd.to_datetime()
df["Join_Date"]=pd.to_datetime(df["Join_Date"],errors="coerce")
df["Join_Date"]

In [ ]:
# Q18. Handle missing dates
# After conversion, find how many missing dates remain.
# Then replace missing dates appropriately using a reasonable date-based strategy.
df["Join_Date"].isnull().sum()

In [ ]:
df["Join_Date"]=df["Join_Date"].fillna(method="ffill")
df["Join_Date"]

In [ ]:
df["Join_Date"].isnull().sum()

#### Part 5 — Categorical Cleaning

In [ ]:
# Q19. Clean City
# The City column contains values such as:
# Mumbai
# mumbai
# Mumbai
# mumbai
# Standardize the values so that logically identical cities are represented consistently.
# Then check the unique frequency distribution.
# Use: replace(), value_counts()
df["City"].replace({"mumbai":"Mumbai"},inplace=True)
df["City"]

In [ ]:
df["City"].value_counts()

In [ ]:
# Q20. Analyze Segment
# Check the frequency of:
# Retail
# SME
# Corporate
# Premium
# Also determine whether missing values exist.
# Then replace missing Segment values with the most appropriate category based on your
# analysis.
# Use: value_counts(), fillna()
df("Segment").value_counts()

In [ ]:
# Q21. Clean Active
# Active is supposed to be a binary column, but it contains:
# Yes
# No
# Y
# N
# YES
# NO
# yes
# no
# 1
# 0
# Transform these into a consistent representation:
# Yes
# No
# Then verify the result with value_counts().
# Use: replace(), value_counts()
df["Active"].replace({"Y":"Yes","YES":"Yes","yes":"Yes","N":"No","NO":"No","no":"No","1":"Yes","0":"No"})

In [ ]:
df["Active"].value_counts()

In [ ]:
# Q22. Clean Risk_Level
# Check the distribution of:
# High
# Medium
# Low
# Verify whether missing values exist.
# Then display the final class distribution.
df["Risk_Level"].value_counts()

In [ ]:
df["Risk_Level"].isnull().sum()

In [ ]:
df["Risk_Level"]=df["Risk_Level"].str.strip()
df["Risk_Level"]

In [ ]:
df["Risk_Level"].value_counts()

#### Part 6 — Column Transformation

In [ ]:

# Q23. Rename columns
# Rename these columns:
# Customer_ID → Customer_ID
# Annual_Income → AnnualIncome
# Account_Balance → AccountBalance
# Credit_Score → CreditScore
# Tenure_Years → Tenure
# Join_Date → CustomerJoinDate
# Risk_Level → RiskLevel
# Monthly_Spend → MonthlySpend
# Satisfaction_Score → SatisfactionScore
# Use rename().
df.rename({"Customer_ID":"CustomerID","Annual_Income":"AnnualIncome","Account_Balance":"AccountBalance","Credit_Score":"CreditScore","Tenure_Years":"Tenure","Join_Date":"CustomerJoinDate","Risk_Level":"RiskLevel","Monthly_Spend":"MonthlySpend","Satisfaction_Score":"SatisfactionScore"},inplace=True)
df

In [ ]:
# Q24. Add a prefix
# Add:
# Customer_
# to every column.
# Example:
# Age
# becomes:
# Customer_Age
# Use: add_prefix()
df.add_prefix("Customer_")

In [ ]:
# Q25. Remove unnecessary column
# Determine whether Customer_ID should be retained for analysis.
# Create a cleaned DataFrame without the identifier column.
# Use: drop()
df1.drop("Channel",axis=1,inplace=True)
df1

#### Part 7 — Create New Columns

In [ ]:
# Q26. Create Annual Income in Lakhs
# Create:
# Income_Lakhs
# using:
# AnnualIncome / 100000
# Then check the first 10 records.
df1["Annual_Income"]=df1["Annual_Income"].str.replace(",","")
df1["Annual_Income"]=pd.to_numeric(df1["Annual_Income"],errors="coerce")
df1["Income_Lakhs"]=df1["Annual_Income"]/100000
df1["Income_Lakhs"]

In [ ]:
df1[["Annual_Income","Income_Lakhs"]].head(10)

In [ ]:
# Q27. Create Monthly Income
# Create:
# MonthlyIncome
# using:
# AnnualIncome / 12
# Then create:
# Income_After_Spending
# using:
# MonthlyIncome - MonthlySpend
df["Annual_Income"]=df["Annual_Income"].str.replace(",","")
df["Annual_Income"]
df["Annual_Income"]=pd.to_numeric(df["Annual_Income"],errors="coerce")
df["MonthlyIncome"]=df["Annual_Income"]/12
df["MonthlyIncome"]

In [ ]:
df["Monthly_Spend"]=df["Monthly_Spend"].str.replace(",","")
df["Monthly_Spend"]
df["Monthly_Spend"]=pd.to_numeric(df["Monthly_Spend"],errors="coerce")
df["Monthly_Spend"]
df["Income_After_Spending"]=df["MonthlyIncome"]-df["Monthly_Spend"]
df["Income_After_Spending"]

In [649]:
# Q28. Create Balance-to-Income Ratio
# Create:
# Balance_Income_Ratio
# using:
# AccountBalance / AnnualIncome
# Then inspect the first 10 rows.

# Sumit Sir Notes
# Think carefully about division by zero and missing values.
import numpy as np
df1["Account_Balance"]=df1["Account_Balance"].str.replace(",","")
df1["Account_Balance"]
df1["Account_Balance"]=pd.to_numeric(df1["Account_Balance"],errors="coerce")


df1["Annual_Income"]=df1["Annual_Income"].str.replace(",","")
df1["Annual_Income"]
df1["Annual_Income"]=pd.to_numeric(df1["Annual_Income"],errors="coerce")

df["Annual_Income"]=df["Annual_Income"].replace(0,np.nan)

df1["Balance_Income_Ratio"]=df1["Account_Balance"]/df1["Annual_Income"]
df1["Balance_Income_Ratio"]

0       2.528805
1       1.180158
2       0.706596
3       3.367435
4       7.678929
          ...
2035    1.733771
2036    1.317158
2037    0.757133
2038    1.066838
2039    1.107312
Name: Balance_Income_Ratio, Length: 2040, dtype: float64

In [651]:
# Part 8 — Final Real-World Cleaning Challenge
# Q29. Prepare the ML-ready dataset
# Perform the following complete pipeline:
# 1. Load the dataset.
# 2. Inspect the first 10 rows.
# 3. Inspect the last 10 rows.
# 4. Inspect 10 random records.
# 5. Run info().
# 6. Check missing values.
# 7. Check duplicates.
# 8. Remove duplicates.
# 9. Clean all numeric columns.
# 10. Convert invalid numeric values to missing.
# 11. Fill numerical missing values appropriately.
# 12. Convert Join_Date to datetime.
# 13. Handle invalid dates.
# 14. Standardize categorical values.
# 15. Clean the binary Active column.
# 16. Rename the columns.
# 17. Remove unnecessary columns.
# 18. Verify the final datatypes.
# 19. Generate descriptive statistics.
# 20. Check categorical distributions.
df2=pd.read_csv("C:\\Users\\vaish\\Downloads\\customer_analytics.csv")
df2.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68.0,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47.0,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65.0,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63.0,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42.0,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

In [653]:
df2.tail(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2030,100122,41.0,201611.0,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61.0,128850.0,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33.0,88037.0,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43.0,122756.0,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18.0,189232.0,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [655]:
df2.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1264,101032,60.0,207268.0,105060.9,733,10,Kolkata,Retail,Agent,2021-09-05 00:00:00,No,Low,31245.7,41,9.0
853,101285,-,34496.0,NaN,unknown,7,Hyderabad,Premium,Agent,2021-05-26 00:00:00,No,Low,12962.09,117,8.0
745,101615,36.0,212772.0,64561.34,365,5,NaN,SME,Branch,2024-10-28 00:00:00,Yes,High,33651.29,22,3.4
1422,101551,46.0,189437.0,196248.05,345,11,Delhi,Premium,Online,2024-09-02 00:00:00,Yes,High,1075.52,19,6.4
1310,100653,34.0,71819.0,212546.91,373,9,Delhi,SME,Online,2021-02-26 00:00:00,Yes,High,42465.62,92,9.1
806,100661,68.0,214420.0,36609.15,797,7,Kolkata,Corporate,Branch,2021-08-11 00:00:00,Yes,Low,48398.53,56,6.5
252,100282,39.0,86681.0,65782.19,573,15,Hyderabad,Premium,Mobile,2023-02-04 00:00:00,No,Medium,3158.01,149,1.9
1816,101664,26.0,233139.0,278074.9,740,3,Kolkata,Corporate,Agent,2022-05-01 00:00:00,No,Low,23940.21,115,5.1
321,101343,32.0,139914.0,284550.88,567,14,Chennai,Retail,Agent,2025-09-09 00:00:00,Yes,Medium,44019.65,116,5.6
1339,100492,49.0,223350.0,197734.13,738,8,Chennai,Premium,Branch,2024-01-18 00:00:00,NO,Low,24653.42,72,2.5

In [657]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [661]:
df2.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [663]:
df2.duplicated().sum()

40

In [669]:
df2.drop_duplicates()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [673]:
select_int=df2.select_dtypes(include=["int"]).columns
for col in select_int:
    df[col]=df[col].astype("float")
print(select_int)

Index(['Customer_ID', 'Tenure_Years'], dtype='object')

In [677]:
df2.fillna(0,inplace=True)
df2

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,0,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,0,Yes,Low,48511.32,119,3.1

In [679]:
df2.fillna(method="ffill")

C:\Users\vaish\AppData\Local\Temp\ipykernel_27164\2723446242.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method="ffill")

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,0,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,0,Yes,Low,48511.32,119,3.1

In [689]:
df2.rename(columns={"Join_Date":"datetime"},inplace=True)
df2

In [695]:
df2["datetime"]=pd.to_datetime(df2["datetime"],errors="coerce")
df2["datetime"]

0             NaT
1             NaT
2             NaT
3             NaT
4             NaT
          ...
2035          NaT
2036          NaT
2037          NaT
2038          NaT
2039   1970-01-01
Name: datetime, Length: 2040, dtype: datetime64[ns]

In [705]:
df["Active"]=df["Active"].str.replace(",","")
df["Active"]

0       Yes
1       Yes
2        No
3       Yes
4        No
       ...
2035     No
2036    Yes
2037    Yes
2038     No
2039    Yes
Name: Active, Length: 2040, dtype: object

In [711]:
df2.rename(columns={"Risk_Level":"RiskLevel","Monthly_Spend":"MonthlySpend"},inplace=True)

In [715]:
df2.drop("City",axis=1)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,Segment,Channel,datetime,Active,RiskLevel,MonthlySpend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,SME,Agent,NaT,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Retail,Agent,NaT,Yes,High,0,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Premium,Agent,NaT,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Premium,Agent,NaT,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,Retail,Agent,NaT,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Retail,Agent,NaT,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Corporate,Agent,NaT,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Retail,Online,NaT,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Retail,Agent,NaT,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Retail,Branch,1970-01-01,Yes,Low,48511.32,119,3.1

In [719]:
df2.dtypes

Customer_ID                    int64
Age                           object
Annual_Income                 object
Account_Balance               object
Credit_Score                  object
Tenure_Years                   int64
City                          object
Segment                       object
Channel                       object
datetime              datetime64[ns]
Active                        object
RiskLevel                     object
MonthlySpend                  object
Transactions                  object
Satisfaction_Score           float64
dtype: object

In [721]:
df2.describe

<bound method NDFrame.describe of       Customer_ID   Age Annual_Income Account_Balance Credit_Score  \
0          101317  55.0       44033.0       111350.85          772
1          101001  32.0      215546.0       254378.37          374
2          101069  23.0      226403.0       159975.42          668
3          101968  66.0       87824.0        295741.6          315
4          100530  67.0       31570.0       242423.78          370
...           ...   ...           ...             ...          ...
2035       101131  42.0       88530.0       153490.72          677
2036       101295  31.0      205738.0        270989.4          392
2037       100861  25.0      211994.0       160507.65          737
2038       101460  64.0       30105.0        32117.15          794
2039       101127  55.0      248332.0       274980.99          783

      Tenure_Years         City    Segment Channel   datetime Active  \
0                3    Bangalore        SME   Agent        NaT    Yes
1                8        Delhi     Retail   Agent        NaT    Yes
2               12      Chennai    Premium   Agent        NaT     No
3               14       Mumbai    Premium   Agent        NaT    Yes
4                4   bangalore      Retail   Agent        NaT     No
...            ...          ...        ...     ...        ...    ...
2035            12    Hyderabad     Retail   Agent        NaT     No
2036             8       Mumbai  Corporate   Agent        NaT    Yes
2037             8      Kolkata     Retail  Online        NaT    Yes
2038             8    Bangalore     Retail   Agent        NaT     No
2039             6      Chennai     Retail  Branch 1970-01-01    Yes

     RiskLevel MonthlySpend Transactions  Satisfaction_Score
0          Low     23066.19          135                 3.1
1         High            0          106                 8.2
2       Medium     28536.34          146                 6.3
3         High     12869.71          115                 9.7
4         High     34163.02           94                 3.7
...        ...          ...          ...                 ...
2035    Medium      8455.42          119                 8.6
2036      High     34087.69          134                 2.6
2037       Low     26518.74           87                 1.3
2038       Low     20943.11          107                 9.3
2039       Low     48511.32          119                 3.1

[2040 rows x 15 columns]>

In [727]:
df2.value_counts()

Customer_ID  Age   Annual_Income  Account_Balance  Credit_Score  Tenure_Years  City         Segment    Channel  datetime    Active  RiskLevel  MonthlySpend  Transactions  Satisfaction_Score
100066       64.0  158541.0       246003.79        725           4             Mumbai       SME        Agent    1970-01-01  Yes     Low        21272.91      43            4.4                   2
101079       43.0  153563.0       18942.09         450           14             bangalore   Retail     Online   1970-01-01  Yes     High       48065.41      111           2.2                   2
101323       34.0  170016.0       218839.13        719           15            Kolkata      0          Branch   1970-01-01  Yes     Low        26574.11      135           8.9                   1
101515       24.0  140359.0       34710.4          524           8             Mumbai       Corporate  Agent    1970-01-01  Yes     High       24760.52      61            3.7                   1
101514       66.0  170361.0       43292.76         672           15            Mumbai       Retail     Mobile   1970-01-01  Yes     Medium     39634.31      91            8.8                   1
                                                                                                                                                                                                ..
100843       58.0  0              76007.15         629           5             Mumbai       Premium    Online   1970-01-01  Yes     Medium     5762.14       129           4.4                   1
100814       30.0  140395.0       0                392           14            Bangalore    0          Mobile   1970-01-01  Yes     High       0             102           5.4                   1
100801       20.0  79253.0        221822.47        656           0             Chennai      Corporate  Agent    1970-01-01  Yes     Medium     20663.08      126           9.1                   1
100791       48.0  185443.0       112066.44        479           11            Delhi        Retail     Agent    1970-01-01  Yes     High       32235.41      55            9.3                   1
101988       34.0  67604.0        185990.57        805           14            Kolkata      SME        Online   1970-01-01  Yes     Low        25733.95      68            1.7                   1
Name: count, Length: 100, dtype: int64

In [ ]:
# Q30 — Ultimate Pandas Cleaning Project
# You are a Data Scientist at a bank. Your raw customer dataset contains 2,000+ records with:

# Sumit Sir Notes
# • Missing values
# • Duplicate records
# • Invalid numerical values
# • Mixed datatypes
# • Invalid dates
# • Mixed date formats
# • Inconsistent categorical values
# • Binary text inconsistencies
# • Unnecessary identifier columns
# Your task is to produce a final clean analytical dataset.

# Required workflow
# Step 1 — Load
# pd.read_csv()
# Step 2 — Inspect
# head()
# tail()
# sample()
# info()

# Step 3 — Missing-value analysis
# isnull()
# isna()

# Step 4 — Duplicate handling
# duplicated()
# drop_duplicates()

# Sumit Sir Notes
# Step 5 — Numeric cleaning
# Clean:
# Age
# Annual_Income
# Account_Balance
# Credit_Score
# Monthly_Spend
# Transactions
# Satisfaction_Score

# Use:
# pd.to_numeric()
# mean()
# median()
# fillna()
# astype()

# Step 6 — Date cleaning
# Clean:
# Join_Date
# using:
# pd.to_datetime()

# Step 7 — Categorical cleaning
# Clean:
# City
# Segment

# Sumit Sir Notes
# Channel
# Active
# Risk_Level
# Use:
# replace()
# value_counts()
# fillna()

# Step 8 — Column transformation
# Use:
# rename()
# add_prefix()
# drop()

# Step 9 — Create analytical features
# Create at least these:
# Income_Lakhs
# MonthlyIncome
# Income_After_Spending
# Balance_Income_Ratio

# Step 10 — Final validation
# Your final DataFrame must pass these checks:
# No duplicate rows
# No invalid numeric values
# No unexpected object datatype in numeric columns
# No invalid dates
# No inconsistent Yes/No values

# Sumit Sir Notes
# Missing values handled
# Column names standardized

# Finally display:
# head()
# tail()
# sample()
# info()
# describe()
# value_counts()

In [729]:
df30=pd.read_csv("C:\\Users\\vaish\\Downloads\\customer_analytics.csv")

In [731]:
df30.head()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7

In [733]:
df30.tail()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [735]:
df30.sample()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
52,100057,31.0,239696.0,41661.4,677,2,Bangalore,NaN,Branch,2022-12-06 00:00:00,YES,Medium,47955.19,115,7.7

In [737]:
df30.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [739]:
df30.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [745]:
df30.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [747]:
df30.duplicated().sum()

40

In [753]:
df30.drop_duplicates()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [862]:
df30["Age"] = df30["Age"].astype(str).str.replace(",", "", regex=False)
df30["Annual_Income"] = df30["Annual_Income"].astype(str).str.replace(",", "", regex=False)
df30["Account_Balance"] = df30["Account_Balance"].astype(str).str.replace(",", "", regex=False)
df30["Credit_Score"] = df30["Credit_Score"].astype(str).str.replace(",", "", regex=False)
df30["Monthly_Spend"] = df30["Monthly_Spend"].astype(str).str.replace(",", "", regex=False)
df30["Transactions"] = df30["Transactions"].astype(str).str.replace(",", "", regex=False)
df30["Satisfaction_Score"] = df30["Satisfaction_Score"].astype(str).str.replace(",", "", regex=False)

In [864]:
df30["Age"]=pd.to_numeric(df30["Age"],errors="coerce")
df30["Annual_Income"]=pd.to_numeric(df30["Annual_Income"],errors="coerce")
df30["Account_Balance"]=pd.to_numeric(df30["Account_Balance"],errors="coerce")
df30["Credit_Score"]=pd.to_numeric(df30["Credit_Score"],errors="coerce")
df30["Monthly_Spend"]=pd.to_numeric(df30["Monthly_Spend"],errors="coerce")
df30["Transactions"]=pd.to_numeric(df30["Transactions"],errors="coerce")
df30["Satisfaction_Score"]=pd.to_numeric(df30["Satisfaction_Score"],errors="coerce")

In [866]:
age_mean=df30["Age"].mean()
df30["Age"]=df30["Age"].fillna(age_mean)

inco_mean=df30["Annual_Income"].mean()
df30["Annual_Income"]=df30["Annual_Income"].fillna(inco_mean)

bal_mean=df30["Account_Balance"].mean()
df30["Account_Balance"]=df30["Account_Balance"].fillna(bal_mean)

score_mean=df30["Credit_Score"].mean()
df30["Credit_Score"]=df30["Credit_Score"].fillna(score_mean)

spend_mean=df30["Monthly_Spend"].mean()
df30["Monthly_Spend"]=df30["Monthly_Spend"].fillna(spend_mean)

trans_mean=df30["Transactions"].mean()
df30["Transactions"]=df30["Transactions"].fillna(trans_mean)

sats_mean=df30["Satisfaction_Score"].mean()
df30["Satisfaction_Score"]=df30["Satisfaction_Score"].fillna(sats_mean)

In [868]:
age_med=df30["Age"].median()
df30["Age"]=df30["Age"].fillna(age_med)

inco_med=df30["Annual_Income"].median()
df30["Annual_Income"]=df30["Annual_Income"].fillna(inco_med)

bal_med=df30["Account_Balance"].median()
df30["Account_Balance"]=df30["Account_Balance"].fillna(bal_med)

score_med=df30["Credit_Score"].median()
df30["Credit_Score"]=df30["Credit_Score"].fillna(score_med)

spend_med=df30["Monthly_Spend"].median()
df30["Monthly_Spend"]=df30["Monthly_Spend"].fillna(spend_med)

trans_med=df30["Transactions"].median()
df30["Transactions"]=df30["Transactions"].fillna(trans_med)

sats_med=df30["Satisfaction_Score"].median()
df30["Satisfaction_Score"]=df30["Satisfaction_Score"].fillna(sats_med)

In [870]:
df30["Age"]=df30["Age"].astype("int")
df30["Annual_Income"]=df30["Annual_Income"].astype("int")
df30["Account_Balance"]=df30["Account_Balance"].astype("int")
df30["Credit_Score"]=df30["Credit_Score"].astype("int")
df30["Monthly_Spend"]=df30["Monthly_Spend"].astype("int")
df30["Transactions"]=df30["Transactions"].astype("int")
df30["Satisfaction_Score"]=df30["Satisfaction_Score"].astype("int")

In [872]:
df30["Join_Date"]=pd.to_datetime(df30["Join_Date"],errors="coerce")
df30["Join_Date"]

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039          NaT
Name: Join_Date, Length: 2000, dtype: datetime64[ns]

In [874]:
columns=["City","Segment","Channel","Active","Risk_Level"]
df30["Active"].replace({"Y":"Yes","YES":"Yes","yes":"Yes","N":"No","NO":"No","no":"No","1":"Yes","0":"No"})
df30["Risk_Level"]=df30["Risk_Level"].replace({"high":"High","medium":"Medium","low":"Low"})

for col in columns:
    df30[col]=df30[col].fillna(df30[col])

for col in columns:
    print("\n",[col])
    print(df30[col].value_counts())

 ['City']
City
Mumbai         286
Hyderabad      274
Delhi          268
Kolkata        260
Pune           253
Chennai        234
Bangalore      230
 mumbai         22
 hyderabad      18
 bangalore      17
 pune           17
 delhi          15
 kolkata        14
 chennai        12
Name: count, dtype: int64

 ['Segment']
Segment
Premium      516
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

 ['Channel']
Channel
Agent     530
Online    497
Branch    493
Mobile    480
Name: count, dtype: int64

 ['Active']
Active
Yes    1288
No      534
Y        17
0        16
N        16
no       16
NO       15
YES      14
yes      14
1        12
Name: count, dtype: int64

 ['Risk_Level']
Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64

In [876]:
# Step 8 — Column transformation
# Use:
# rename()
# add_prefix()
# drop()
df30.add_prefix("CUST_")

,CUST_Customer_ID,CUST_Age,CUST_Annual_Income,CUST_Account_Balance,CUST_Credit_Score,CUST_Tenure_Years,CUST_City,CUST_Segment,CUST_Channel,CUST_Join_Date,CUST_Active,CUST_Risk_Level,CUST_Monthly_Spend,CUST_Transactions,CUST_Satisfaction_Score,CUST_Income_Lakhs,CUST_MonthlyIncome,CUST_Income_After_Spending,CUST_Balance_Income_Ratio
0,101317,55,44033,111350,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066,135,3,0.044033,88284,88284,2.528785
1,101001,32,215546,254378,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24646,106,8,0.215546,229732,229732,1.180156
2,101069,23,226403,159975,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536,146,6,0.226403,131439,131439,0.706594
3,101968,66,87824,295741,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869,115,9,0.087824,282872,282872,3.367428
4,100530,67,31570,242423,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163,94,3,0.031570,208260,208260,7.678904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455,119,8,0.088530,145035,145035,1.733763
2036,101295,31,205738,270989,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087,134,2,0.205738,236902,236902,1.317156
2037,100861,25,211994,160507,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518,87,1,0.211994,133989,133989,0.757130
2038,101460,64,30105,32117,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943,107,9,0.030105,11174,11174,1.066833
2039,101127,55,248332,274980,783,6,Chennai,Retail,Branch,NaT,Yes,Low,48511,119,3,0.248332,226469,226469,1.107308

In [878]:
df30.drop("Tenure_Years",axis=1)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,101317,55,44033,111350,772,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066,135,3,0.044033,88284,88284,2.528785
1,101001,32,215546,254378,374,Delhi,Retail,Agent,2025-01-11,Yes,High,24646,106,8,0.215546,229732,229732,1.180156
2,101069,23,226403,159975,668,Chennai,Premium,Agent,2024-08-01,No,Medium,28536,146,6,0.226403,131439,131439,0.706594
3,101968,66,87824,295741,315,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869,115,9,0.087824,282872,282872,3.367428
4,100530,67,31570,242423,370,bangalore,Retail,Agent,2026-02-03,No,High,34163,94,3,0.031570,208260,208260,7.678904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490,677,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455,119,8,0.088530,145035,145035,1.733763
2036,101295,31,205738,270989,392,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087,134,2,0.205738,236902,236902,1.317156
2037,100861,25,211994,160507,737,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518,87,1,0.211994,133989,133989,0.757130
2038,101460,64,30105,32117,794,Bangalore,Retail,Agent,2023-08-26,No,Low,20943,107,9,0.030105,11174,11174,1.066833
2039,101127,55,248332,274980,783,Chennai,Retail,Branch,NaT,Yes,Low,48511,119,3,0.248332,226469,226469,1.107308

In [880]:
# Step 9 — Create analytical features
# Create at least these:
# Income_Lakhs
# MonthlyIncome
# Income_After_Spending
# Balance_Income_Ratio
df30["Income_Lakhs"]=df30["Annual_Income"]/1000000
df30["Income_Lakhs"]

0       0.044033
1       0.215546
2       0.226403
3       0.087824
4       0.031570
          ...
2035    0.088530
2036    0.205738
2037    0.211994
2038    0.030105
2039    0.248332
Name: Income_Lakhs, Length: 2000, dtype: float64

In [882]:
df30["Income_After_Spending"]=df30["Account_Balance"]-df30["Monthly_Spend"]
df30["Income_After_Spending"]

0        88284
1       229732
2       131439
3       282872
4       208260
         ...
2035    145035
2036    236902
2037    133989
2038     11174
2039    226469
Name: Income_After_Spending, Length: 2000, dtype: int32

In [884]:
df30["Balance_Income_Ratio"]=df30["Account_Balance"]/df30["Annual_Income"]
df30["Balance_Income_Ratio"]

0       2.528785
1       1.180156
2       0.706594
3       3.367428
4       7.678904
          ...
2035    1.733763
2036    1.317156
2037    0.757130
2038    1.066833
2039    1.107308
Name: Balance_Income_Ratio, Length: 2000, dtype: float64

In [886]:
# Step 10 — Final validation
# Your final DataFrame must pass these checks:
# No duplicate rows
# No invalid numeric values
# No unexpected object datatype in numeric columns
# No invalid dates
# No inconsistent Yes/No values
df30.drop_duplicates(inplace=True)

In [888]:
df30.duplicated().sum()

0

In [890]:
df30.isnull().sum()

Customer_ID                0
Age                        0
Annual_Income              0
Account_Balance            0
Credit_Score               0
Tenure_Years               0
City                      80
Segment                  100
Channel                    0
Join_Date                125
Active                    58
Risk_Level                 0
Monthly_Spend              0
Transactions               0
Satisfaction_Score         0
Income_Lakhs               0
MonthlyIncome              0
Income_After_Spending      0
Balance_Income_Ratio       0
dtype: int64

In [893]:
df30.value_counts(dropna=False).sum()

2000

In [895]:
print(df[columns].dtypes)
df["Channel"]=df["Channel"].astype()

City          float64
Segment       float64
Channel        object
Active        float64
Risk_Level     object
dtype: object

In [897]:
print(df["Join_Date"].dtypes)

float64

In [899]:
df["Active"].value_counts(dropna=False)

Active
0.0    2028
1.0      12
Name: count, dtype: int64

In [902]:
df30.head()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,101317,55,44033,111350,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066,135,3,0.044033,88284,88284,2.528785
1,101001,32,215546,254378,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24646,106,8,0.215546,229732,229732,1.180156
2,101069,23,226403,159975,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536,146,6,0.226403,131439,131439,0.706594
3,101968,66,87824,295741,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869,115,9,0.087824,282872,282872,3.367428
4,100530,67,31570,242423,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163,94,3,0.031570,208260,208260,7.678904

In [904]:
df30.tail()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
2035,101131,42,88530,153490,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455,119,8,0.088530,145035,145035,1.733763
2036,101295,31,205738,270989,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087,134,2,0.205738,236902,236902,1.317156
2037,100861,25,211994,160507,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518,87,1,0.211994,133989,133989,0.757130
2038,101460,64,30105,32117,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943,107,9,0.030105,11174,11174,1.066833
2039,101127,55,248332,274980,783,6,Chennai,Retail,Branch,NaT,Yes,Low,48511,119,3,0.248332,226469,226469,1.107308

In [906]:
df30.sample()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
597,100507,71,195102,219636,843,1,NaN,Retail,Online,2021-10-03,No,Low,24646,65,4,0.195102,194990,194990,1.12575

In [908]:
df30.describe()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,Join_Date,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,1875,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,101000.500000,47.006000,138368.333500,151563.29300,576.241500,7.574000,2023-08-23 23:13:55.200000,24847.278500,75.46050,5.150000,0.138368,126716.014500,126716.014500,1.497461
min,100001.000000,18.000000,25163.000000,55.00000,300.000000,0.000000,2021-01-01 00:00:00,559.000000,1.00000,1.000000,0.025163,-47657.000000,-47657.000000,0.000277
25%,100500.750000,34.000000,88617.000000,83956.00000,434.000000,4.000000,2022-05-15 00:00:00,13114.500000,40.00000,3.000000,0.088617,59439.750000,59439.750000,0.614240
50%,101000.500000,47.000000,139999.000000,153954.00000,570.000000,8.000000,2023-08-24 00:00:00,24646.000000,76.00000,5.000000,0.139999,129653.000000,129653.000000,1.105976
75%,101500.250000,61.000000,188465.000000,219656.00000,720.250000,12.000000,2024-11-30 12:00:00,36337.250000,112.00000,7.000000,0.188465,194895.500000,194895.500000,1.836130
max,102000.000000,75.000000,249977.000000,299914.00000,850.000000,15.000000,2026-03-13 00:00:00,49942.000000,149.00000,10.000000,0.249977,294720.000000,294720.000000,11.427453
std,577.494589,16.184991,61981.741024,82603.44287,160.930521,4.610548,NaN,13850.594103,42.57714,2.518069,0.061982,83991.924099,83991.924099,1.451527

In [914]:
df30.value_counts()

Customer_ID  Age  Annual_Income  Account_Balance  Credit_Score  Tenure_Years  City       Segment    Channel  Join_Date   Active  Risk_Level  Monthly_Spend  Transactions  Satisfaction_Score  Income_Lakhs  MonthlyIncome  Income_After_Spending  Balance_Income_Ratio
100003       46   108560         249995           712           3             Delhi      SME        Mobile   2021-02-21  Yes     Low         26986          120           5                   0.108560      223009         223009                 2.302828                1
101311       25   92695          147229           558           3             Kolkata    SME        Branch   2022-09-22  Yes     Medium      18142          131           4                   0.092695      129087         129087                 1.588317                1
101324       50   44873          171966           540           5             Mumbai     SME        Agent    2023-04-05  No      High        27122          129           5                   0.044873      144844         144844                 3.832282                1
101322       42   140725         101244           561           13            Bangalore  Premium    Agent    2022-09-15  Yes     Medium      24646          27            3                   0.140725      76598          76598                  0.719446                1
101321       50   219509         268195           440           3             Pune       Premium    Online   2024-11-11  Yes     High        1974           128           8                   0.219509      266221         266221                 1.221795                1
                                                                                                                                                                                                                                                                         ..
100651       52   183670         168027           508           6             Kolkata    Corporate  Branch   2024-01-04  Yes     High        13938          115           8                   0.183670      154089         154089                 0.914831                1
100649       68   78551          189647           525           3             Pune       Retail     Branch   2024-10-23  Yes     High        1042           16            9                   0.078551      188605         188605                 2.414317                1
100648       19   106889         284762           389           10            Pune       SME        Branch   2023-03-30  Yes     High        44420          28            1                   0.106889      240342         240342                 2.664091                1
100647       63   46636          108513           309           5             Bangalore  Corporate  Agent    2023-11-10  Yes     High        43762          44            3                   0.046636      64751          64751                  2.326808                1
102000       31   79245          44508            324           6             Bangalore  Premium    Online   2025-12-24  Yes     High        5314           16            1                   0.079245      39194          39194                  0.561651                1
Name: count, Length: 1663, dtype: int64

In [916]:
df30.to_csv("Clean_data.csv")