#### Flight Price Datasets— 30 Clean Questions

In [928]:
#1. Load the Flight Price dataset into a Pandas DataFrame and display the first
#five rows.
import pandas as pd
df=pd.read_excel("C:/Users/vaish/Downloads/Data_Train.xlsx")
df.head(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [929]:
# 2. Find the number of rows and columns in the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [930]:
# 3. Display all column names in the dataset.
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [931]:
# 4. Display the data types of all columns.
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [936]:
# 5. Use df.info() to inspect the structure of the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [938]:
# 6. Check the number of missing values in each column.
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [940]:
# 7. Check the percentage of missing values in each column.
df.isnull().sum()/100

Airline            0.00
Date_of_Journey    0.00
Source             0.00
Destination        0.00
Route              0.01
Dep_Time           0.00
Arrival_Time       0.00
Duration           0.00
Total_Stops        0.01
Additional_Info    0.00
Price              0.00
dtype: float64

In [942]:
# 8. Display the unique values and frequency of each value in the Airline column.
df["Airline"].nunique()

12

In [944]:
df["Airline"].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [946]:
# 9. Display the frequency distribution of Total_Stops, including missing values.
df["Total_Stops"].value_counts(dropna=False)

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
NaN            1
4 stops        1
Name: count, dtype: int64

In [948]:
# 10.Convert Date_of_Journey into a datetime format.
df["Date_of_Journey"]=pd.to_datetime(df["Date_of_Journey"],errors="coerce")
df["Date_of_Journey"]

C:\Users\vaish\AppData\Local\Temp\ipykernel_19028\2079656835.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Date_of_Journey"]=pd.to_datetime(df["Date_of_Journey"],errors="coerce")

0       2019-03-24
1       2019-05-01
2       2019-06-09
3       2019-05-12
4       2019-03-01
           ...
10678   2019-04-09
10679   2019-04-27
10680   2019-04-27
10681   2019-03-01
10682   2019-05-09
Name: Date_of_Journey, Length: 10683, dtype: datetime64[ns]

In [950]:
# 11.Extract the day from Date_of_Journey and create a day column.
df["day"]=df["Date_of_Journey"].dt.day
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9
10679,Air India,2019-04-27,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27
10680,Jet Airways,2019-04-27,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27
10681,Vistara,2019-03-01,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1
10682,Air India,2019-05-09,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9

In [952]:
# 12.Extract the month from Date_of_Journey and create a month column.
df["month"]=df["Date_of_Journey"].dt.month
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4
10679,Air India,2019-04-27,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4
10680,Jet Airways,2019-04-27,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4
10681,Vistara,2019-03-01,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3
10682,Air India,2019-05-09,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5

In [954]:
# 13.Extract the year from Date_of_Journey and create a year column.
df["year"]=df["Date_of_Journey"].dt.year
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,2019-04-27,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,2019-04-27,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,2019-03-01,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,2019-05-09,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [956]:
# 14.Drop the original Date_of_Journey column after extracting the required
# features.
df.drop("Date_of_Journey",axis=1,inplace=True)

In [958]:
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [960]:
# 15.Convert Dep_Time into datetime format and extract the departure hour into
# Dep_Hour.
df["Dep_Time"]=pd.to_datetime(df["Dep_Time"],errors="coerce")
df["Dep_Time"]

C:\Users\vaish\AppData\Local\Temp\ipykernel_19028\1233332289.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Dep_Time"]=pd.to_datetime(df["Dep_Time"],errors="coerce")

0       2026-08-10 22:20:00
1       2026-08-10 05:50:00
2       2026-08-10 09:25:00
3       2026-08-10 18:05:00
4       2026-08-10 16:50:00
                ...
10678   2026-08-10 19:55:00
10679   2026-08-10 20:45:00
10680   2026-08-10 08:20:00
10681   2026-08-10 11:30:00
10682   2026-08-10 10:55:00
Name: Dep_Time, Length: 10683, dtype: datetime64[ns]

In [962]:
df["Dep_Hour"]=df["Dep_Time"].dt.hour
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour
0,IndiGo,Banglore,New Delhi,BLR → DEL,2026-08-10 22:20:00,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-08-10 05:50:00,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2026-08-10 09:25:00,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,9
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,2026-08-10 18:05:00,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,2026-08-10 16:50:00,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2026-08-10 19:55:00,22:25,2h 30m,non-stop,No info,4107,9,4,2019,19
10679,Air India,Kolkata,Banglore,CCU → BLR,2026-08-10 20:45:00,23:20,2h 35m,non-stop,No info,4145,27,4,2019,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,2026-08-10 08:20:00,11:20,3h,non-stop,No info,7229,27,4,2019,8
10681,Vistara,Banglore,New Delhi,BLR → DEL,2026-08-10 11:30:00,14:10,2h 40m,non-stop,No info,12648,1,3,2019,11
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2026-08-10 10:55:00,19:15,8h 20m,2 stops,No info,11753,9,5,2019,10

In [964]:
# 16.Extract the departure minute from Dep_Time and create Dep_Minute.
df["Dep_Minute"]=df["Dep_Time"].dt.minute
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2026-08-10 22:20:00,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-08-10 05:50:00,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2026-08-10 09:25:00,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,2026-08-10 18:05:00,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,2026-08-10 16:50:00,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2026-08-10 19:55:00,22:25,2h 30m,non-stop,No info,4107,9,4,2019,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,2026-08-10 20:45:00,23:20,2h 35m,non-stop,No info,4145,27,4,2019,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,2026-08-10 08:20:00,11:20,3h,non-stop,No info,7229,27,4,2019,8,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2026-08-10 11:30:00,14:10,2h 40m,non-stop,No info,12648,1,3,2019,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2026-08-10 10:55:00,19:15,8h 20m,2 stops,No info,11753,9,5,2019,10,55

In [966]:
# 17.Drop the original Dep_Time column after extracting the required features.
df.drop("Dep_Time",axis=1,inplace=True)
df

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,22:25,2h 30m,non-stop,No info,4107,9,4,2019,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,23:20,2h 35m,non-stop,No info,4145,27,4,2019,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,11:20,3h,non-stop,No info,7229,27,4,2019,8,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,14:10,2h 40m,non-stop,No info,12648,1,3,2019,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,19:15,8h 20m,2 stops,No info,11753,9,5,2019,10,55

In [968]:
# 18.Extract only the time portion from Arrival_Time.
#df["Arrival_Time"]=df["Arrival_Time"].str.split().str[0]
df["Arrival_Time"]=pd.to_datetime(df["Arrival_Time"],errors="coerce")
df["Arrival_Time"]

C:\Users\vaish\AppData\Local\Temp\ipykernel_19028\3953330378.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Arrival_Time"]=pd.to_datetime(df["Arrival_Time"],errors="coerce")

0       2026-03-22 01:10:00
1       2026-08-10 13:15:00
2       2026-06-10 04:25:00
3       2026-08-10 23:30:00
4       2026-08-10 21:35:00
                ...
10678   2026-08-10 22:25:00
10679   2026-08-10 23:20:00
10680   2026-08-10 11:20:00
10681   2026-08-10 14:10:00
10682   2026-08-10 19:15:00
Name: Arrival_Time, Length: 10683, dtype: datetime64[ns]

In [971]:
# 19.Extract the arrival hour and minute into Arrival_Hour and Arrival_Minute.
df["Arrival_Hour"]=df["Arrival_Time"].dt.hour
df

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour
0,IndiGo,Banglore,New Delhi,BLR → DEL,2026-03-22 01:10:00,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-08-10 13:15:00,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2026-06-10 04:25:00,19h,2 stops,No info,13882,9,6,2019,9,25,4
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,2026-08-10 23:30:00,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,2026-08-10 21:35:00,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2026-08-10 22:25:00,2h 30m,non-stop,No info,4107,9,4,2019,19,55,22
10679,Air India,Kolkata,Banglore,CCU → BLR,2026-08-10 23:20:00,2h 35m,non-stop,No info,4145,27,4,2019,20,45,23
10680,Jet Airways,Banglore,Delhi,BLR → DEL,2026-08-10 11:20:00,3h,non-stop,No info,7229,27,4,2019,8,20,11
10681,Vistara,Banglore,New Delhi,BLR → DEL,2026-08-10 14:10:00,2h 40m,non-stop,No info,12648,1,3,2019,11,30,14
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2026-08-10 19:15:00,8h 20m,2 stops,No info,11753,9,5,2019,10,55,19

In [973]:
df["Arrival_Minute"]=df["Arrival_Time"].dt.minute
df

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2026-03-22 01:10:00,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-08-10 13:15:00,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2026-06-10 04:25:00,19h,2 stops,No info,13882,9,6,2019,9,25,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,2026-08-10 23:30:00,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,2026-08-10 21:35:00,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2026-08-10 22:25:00,2h 30m,non-stop,No info,4107,9,4,2019,19,55,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,2026-08-10 23:20:00,2h 35m,non-stop,No info,4145,27,4,2019,20,45,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,2026-08-10 11:20:00,3h,non-stop,No info,7229,27,4,2019,8,20,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2026-08-10 14:10:00,2h 40m,non-stop,No info,12648,1,3,2019,11,30,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2026-08-10 19:15:00,8h 20m,2 stops,No info,11753,9,5,2019,10,55,19,15

In [975]:
# 20.Drop the original Arrival_Time column after extracting the required features.
df.drop("Arrival_Time",axis=1,inplace=True)

In [977]:
df

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,9,25,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,non-stop,No info,4107,9,4,2019,19,55,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,non-stop,No info,4145,27,4,2019,20,45,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,non-stop,No info,7229,27,4,2019,8,20,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,non-stop,No info,12648,1,3,2019,11,30,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2 stops,No info,11753,9,5,2019,10,55,19,15

In [979]:
# 21.Extract the hour component from Duration and create Duration_Hour. Handle
# invalid or missing extracted values appropriately.
df["Duration_Hour"]=df["Duration"].str.split("h").str[0]

In [981]:
df["Duration_Hour"]=pd.to_numeric(df["Duration_Hour"],errors="coerce")

In [983]:
due_median=df["Duration_Hour"].median()
df["Duration_Hour"]=df["Duration_Hour"].fillna(due_median)

In [985]:
df[["Duration_Hour","Duration"]].head()

   Duration_Hour Duration
0            2.0   2h 50m
1            7.0   7h 25m
2           19.0      19h
3            5.0   5h 25m
4            4.0   4h 45m

In [987]:
df

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10,2.0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15,7.0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,9,25,4,25,19.0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30,5.0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,non-stop,No info,4107,9,4,2019,19,55,22,25,2.0
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,non-stop,No info,4145,27,4,2019,20,45,23,20,2.0
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,non-stop,No info,7229,27,4,2019,8,20,11,20,3.0
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,non-stop,No info,12648,1,3,2019,11,30,14,10,2.0
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2 stops,No info,11753,9,5,2019,10,55,19,15,8.0

In [989]:
# 22.Extract the minute component from Duration and create Duration_Minute.
# Handle invalid or missing extracted values appropriately.
df["Duration_Minute"]=df["Duration"].str.split(" ").str[1].str.replace("m"," ")
df["Duration_Minute"]=pd.to_numeric(df["Duration_Minute"],errors="coerce")
min_med=df["Duration_Minute"].median()
df["Duration_Minute"]=df["Duration_Minute"].fillna(min_med)
df

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10,2.0,50.0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15,7.0,25.0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,9,25,4,25,19.0,30.0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30,5.0,25.0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35,4.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,non-stop,No info,4107,9,4,2019,19,55,22,25,2.0,30.0
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,non-stop,No info,4145,27,4,2019,20,45,23,20,2.0,35.0
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,non-stop,No info,7229,27,4,2019,8,20,11,20,3.0,30.0
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,non-stop,No info,12648,1,3,2019,11,30,14,10,2.0,40.0
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2 stops,No info,11753,9,5,2019,10,55,19,15,8.0,20.0

In [991]:
# 23.Drop the original Duration column after creating the numerical duration
# features.
df.drop("Duration",axis=1,inplace=True)

In [993]:
df

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,24,3,2019,22,20,1,10,2.0,50.0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,1,5,2019,5,50,13,15,7.0,25.0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,6,2019,9,25,4,25,19.0,30.0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,12,5,2019,18,5,23,30,5.0,25.0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,1,3,2019,16,50,21,35,4.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,non-stop,No info,4107,9,4,2019,19,55,22,25,2.0,30.0
10679,Air India,Kolkata,Banglore,CCU → BLR,non-stop,No info,4145,27,4,2019,20,45,23,20,2.0,35.0
10680,Jet Airways,Banglore,Delhi,BLR → DEL,non-stop,No info,7229,27,4,2019,8,20,11,20,3.0,30.0
10681,Vistara,Banglore,New Delhi,BLR → DEL,non-stop,No info,12648,1,3,2019,11,30,14,10,2.0,40.0
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2 stops,No info,11753,9,5,2019,10,55,19,15,8.0,20.0

In [995]:
# 24.Replace non-stop in Total_Stops with 0 stops.
df.replace({"Total_Stops":{"non-stop":0}},inplace=True)
df

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,3,2019,22,20,1,10,2.0,50.0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,1,5,2019,5,50,13,15,7.0,25.0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,6,2019,9,25,4,25,19.0,30.0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,12,5,2019,18,5,23,30,5.0,25.0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,1,3,2019,16,50,21,35,4.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,0,No info,4107,9,4,2019,19,55,22,25,2.0,30.0
10679,Air India,Kolkata,Banglore,CCU → BLR,0,No info,4145,27,4,2019,20,45,23,20,2.0,35.0
10680,Jet Airways,Banglore,Delhi,BLR → DEL,0,No info,7229,27,4,2019,8,20,11,20,3.0,30.0
10681,Vistara,Banglore,New Delhi,BLR → DEL,0,No info,12648,1,3,2019,11,30,14,10,2.0,40.0
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2 stops,No info,11753,9,5,2019,10,55,19,15,8.0,20.0

In [1005]:
# 25.Extract only the numerical value from Total_Stops and convert the column into
# an integer data type. Handle missing or invalid values appropriately.

df["Total_Stops"]=df["Total_Stops"].replace({
    "non-stop":0,"1 stop":1,"2 stops":2,"3 stops":3,"4 stops":4
})

C:\Users\vaish\AppData\Local\Temp\ipykernel_19028\283652956.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Total_Stops"]=df["Total_Stops"].replace({

In [1007]:

df["Total_Stops"]=df["Total_Stops"].fillna(0)

In [1009]:

df["Total_Stops"]=df["Total_Stops"].astype("int")

In [1011]:
df["Total_Stops"].head()

0    0
1    2
2    2
3    1
4    1
Name: Total_Stops, dtype: int32

In [1013]:
df["Total_Stops"].unique()

array([0, 2, 1, 3, 4])

In [1015]:
# 26.Split the Route column using → as the separator and create Route_1,
# Route_2, Route_3, Route_4, and Route_5.
route=df["Route"].str.split("→",expand=True)

In [1017]:
df["Route_1"]=route[0].str.strip()
df["Route_2"]=route[1].str.strip()
df["Route_3"]=route[2].str.strip()
df["Route_4"]=route[3].str.strip()
df["Route_5"]=route[4].str.strip()
df["Route_6"]=route[5].str.strip()

In [1019]:
df

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,...,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5,Route_6
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,3,2019,...,1,10,2.0,50.0,BLR,DEL,None,None,None,None
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,1,5,2019,...,13,15,7.0,25.0,CCU,IXR,BBI,BLR,None,None
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,6,2019,...,4,25,19.0,30.0,DEL,LKO,BOM,COK,None,None
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,12,5,2019,...,23,30,5.0,25.0,CCU,NAG,BLR,None,None,None
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,1,3,2019,...,21,35,4.0,45.0,BLR,NAG,DEL,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,0,No info,4107,9,4,2019,...,22,25,2.0,30.0,CCU,BLR,None,None,None,None
10679,Air India,Kolkata,Banglore,CCU → BLR,0,No info,4145,27,4,2019,...,23,20,2.0,35.0,CCU,BLR,None,None,None,None
10680,Jet Airways,Banglore,Delhi,BLR → DEL,0,No info,7229,27,4,2019,...,11,20,3.0,30.0,BLR,DEL,None,None,None,None
10681,Vistara,Banglore,New Delhi,BLR → DEL,0,No info,12648,1,3,2019,...,14,10,2.0,40.0,BLR,DEL,None,None,None,None
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2,No info,11753,9,5,2019,...,19,15,8.0,20.0,DEL,GOI,BOM,COK,None,None

In [1021]:
# 27.Identify the missing values created in Route_3, Route_4, and Route_5 after
# splitting the route.
df[["Route_3","Route_4","Route_5"]].isnull().sum()

Route_3     3492
Route_4     9117
Route_5    10637
dtype: int64

In [1023]:
df

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,...,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5,Route_6
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,3,2019,...,1,10,2.0,50.0,BLR,DEL,None,None,None,None
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,1,5,2019,...,13,15,7.0,25.0,CCU,IXR,BBI,BLR,None,None
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,6,2019,...,4,25,19.0,30.0,DEL,LKO,BOM,COK,None,None
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,12,5,2019,...,23,30,5.0,25.0,CCU,NAG,BLR,None,None,None
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,1,3,2019,...,21,35,4.0,45.0,BLR,NAG,DEL,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,0,No info,4107,9,4,2019,...,22,25,2.0,30.0,CCU,BLR,None,None,None,None
10679,Air India,Kolkata,Banglore,CCU → BLR,0,No info,4145,27,4,2019,...,23,20,2.0,35.0,CCU,BLR,None,None,None,None
10680,Jet Airways,Banglore,Delhi,BLR → DEL,0,No info,7229,27,4,2019,...,11,20,3.0,30.0,BLR,DEL,None,None,None,None
10681,Vistara,Banglore,New Delhi,BLR → DEL,0,No info,12648,1,3,2019,...,14,10,2.0,40.0,BLR,DEL,None,None,None,None
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2,No info,11753,9,5,2019,...,19,15,8.0,20.0,DEL,GOI,BOM,COK,None,None

In [1025]:
# 28.Replace the missing values in the route columns with an appropriate value
# such as None.
df[["Route_1","Route_2","Route_3","Route_4","Route_5"]]=df[["Route_1","Route_2","Route_3","Route_4","Route_5"]].fillna("None")

In [1027]:
df

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,...,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5,Route_6
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,3,2019,...,1,10,2.0,50.0,BLR,DEL,None,None,None,None
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,1,5,2019,...,13,15,7.0,25.0,CCU,IXR,BBI,BLR,None,None
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,6,2019,...,4,25,19.0,30.0,DEL,LKO,BOM,COK,None,None
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,12,5,2019,...,23,30,5.0,25.0,CCU,NAG,BLR,None,None,None
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,1,3,2019,...,21,35,4.0,45.0,BLR,NAG,DEL,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,0,No info,4107,9,4,2019,...,22,25,2.0,30.0,CCU,BLR,None,None,None,None
10679,Air India,Kolkata,Banglore,CCU → BLR,0,No info,4145,27,4,2019,...,23,20,2.0,35.0,CCU,BLR,None,None,None,None
10680,Jet Airways,Banglore,Delhi,BLR → DEL,0,No info,7229,27,4,2019,...,11,20,3.0,30.0,BLR,DEL,None,None,None,None
10681,Vistara,Banglore,New Delhi,BLR → DEL,0,No info,12648,1,3,2019,...,14,10,2.0,40.0,BLR,DEL,None,None,None,None
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2,No info,11753,9,5,2019,...,19,15,8.0,20.0,DEL,GOI,BOM,COK,None,None

In [1029]:
# 29.Drop the original Route column after creating and cleaning the route features.
df.drop("Route",axis=1,inplace=True)

In [1031]:
df

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,...,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5,Route_6
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,22,...,1,10,2.0,50.0,BLR,DEL,None,None,None,None
1,Air India,Kolkata,Banglore,2,No info,7662,1,5,2019,5,...,13,15,7.0,25.0,CCU,IXR,BBI,BLR,None,None
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,6,2019,9,...,4,25,19.0,30.0,DEL,LKO,BOM,COK,None,None
3,IndiGo,Kolkata,Banglore,1,No info,6218,12,5,2019,18,...,23,30,5.0,25.0,CCU,NAG,BLR,None,None,None
4,IndiGo,Banglore,New Delhi,1,No info,13302,1,3,2019,16,...,21,35,4.0,45.0,BLR,NAG,DEL,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,0,No info,4107,9,4,2019,19,...,22,25,2.0,30.0,CCU,BLR,None,None,None,None
10679,Air India,Kolkata,Banglore,0,No info,4145,27,4,2019,20,...,23,20,2.0,35.0,CCU,BLR,None,None,None,None
10680,Jet Airways,Banglore,Delhi,0,No info,7229,27,4,2019,8,...,11,20,3.0,30.0,BLR,DEL,None,None,None,None
10681,Vistara,Banglore,New Delhi,0,No info,12648,1,3,2019,11,...,14,10,2.0,40.0,BLR,DEL,None,None,None,None
10682,Air India,Delhi,Cochin,2,No info,11753,9,5,2019,10,...,19,15,8.0,20.0,DEL,GOI,BOM,COK,None,None

In [1033]:
# 30.After completing all data cleaning and feature engineering, separate the
# dataset into X (independent variables) and y (target variable), where Price
# is the target.
X=df[['Airline', 'Source', 'Destination', 'Total_Stops', 'Additional_Info',
        'day', 'month', 'year', 'Dep_Hour', 'Dep_Minute',
       'Arrival_Hour', 'Arrival_Minute', 'Duration_Hour', 'Duration_Minute',
       'Route_1', 'Route_2', 'Route_3', 'Route_4', 'Route_5', 'Route_6']]
Y=df["Price"]

In [1035]:
X.shape

(10683, 20)

In [1037]:
Y.shape

(10683,)

In [1039]:
df.to_csv("Cleaned_Flight_Price_Dataset")