### 30 practical data-cleaning questions

In [537]:
# Basic Cleaning
# 1. Load the CSV file using Pandas and display the first 10 rows.
import pandas as pd
df=pd.read_csv("C:\\Users\\vaish\\Downloads\\messy_customer_loan_dataset.csv")
df.head(10)

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
5,CUST100925,32.0,317590.0,690.0,Salaried,Graduate,M,Mumbai,Premium,Auto,235549.0,120,5.0,0.46,No
6,CUST100758,39.0,322966.0,707.0,Contract,Graduate,Married,Chennai,Mass,Personal,563319.0,24,7.0,0.323,No
7,CUST100793,54.0,999108.0,689.0,Salaried,Graduate,Divorced,Hyderabad,SME,Auto,767783.0,48,NaN,0.233,Yes
8,CUST100965,65.0,478191.0,758.0,Contract,Graduate,Divorced,Bengaluru,premium,Auto,753872.0,72,5.0,0.375,No
9,CUST101198,67.0,1063307.0,774.0,SALARIED,Graduate,Married,Jaipur,Affluent,Home,549693.0,120,2.0,0.394,Yes

In [539]:
# 2. Display the number of rows and columns in the dataset.
df.shape

(1535, 15)

In [541]:
# 3. Display all column names and identify which column names have
# leading/trailing spaces.
df.columns

Index([' Customer ID ', 'Age ', 'Annual Income', 'credit Score ',
       'Employment-Type', 'Education  Level', 'marital_status', 'city',
       'customer_segment ', 'loan_type', 'Loan Amount (INR)', 'tenure Months',
       'Monthly Visits ', 'debt_to_income', 'Loan Approved?'],
      dtype='object')

In [543]:
# 4. Clean all column names by removing extra spaces and converting them into a
# consistent format such as snake_case.
df.columns=df.columns.str.strip().str.lower().str.replace(" ","_").str.replace("-","_").str.replace("__","_")
df.columns

Index(['customer_id', 'age', 'annual_income', 'credit_score',
       'employment_type', 'education_level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'loan_amount_(inr)', 'tenure_months',
       'monthly_visits', 'debt_to_income', 'loan_approved?'],
      dtype='object')

In [545]:
# 5. Check the data type of every column.
df.dtypes

customer_id          object
age                  object
annual_income        object
credit_score         object
employment_type      object
education_level      object
marital_status       object
city                 object
customer_segment     object
loan_type            object
loan_amount_(inr)    object
tenure_months         int64
monthly_visits       object
debt_to_income       object
loan_approved?       object
dtype: object

In [547]:
# 6. Find the total number of missing values in each column.
df.isnull().sum()

customer_id            0
age                   71
annual_income         84
credit_score          77
employment_type       60
education_level       46
marital_status         0
city                  52
customer_segment       0
loan_type              0
loan_amount_(inr)    102
tenure_months          0
monthly_visits        55
debt_to_income        89
loan_approved?         0
dtype: int64

In [549]:
# 7. Find the percentage of missing values in each column.
df.isnull().sum()/100

customer_id          0.00
age                  0.71
annual_income        0.84
credit_score         0.77
employment_type      0.60
education_level      0.46
marital_status       0.00
city                 0.52
customer_segment     0.00
loan_type            0.00
loan_amount_(inr)    1.02
tenure_months        0.00
monthly_visits       0.55
debt_to_income       0.89
loan_approved?       0.00
dtype: float64

In [551]:
# 8. Find all rows where Age is missing.
df["age"].isnull().sum()

71

In [553]:
# 9. Find all rows where Annual Income is missing.
df["annual_income"].isnull().sum()

84

In [555]:
# 10.Remove completely duplicate rows and report how many duplicate rows were
# removed.
df.duplicated().sum()

35

In [557]:
df.drop_duplicates(inplace=True)

In [559]:
df.duplicated().sum()

0

#### Data Type & Invalid Values

In [562]:
# 11.The Age column contains numbers as well as values like "unknown" and
# "twenty five". Clean this column and convert it into a proper numeric column.
df["age"]=pd.to_numeric(df["age"],errors="coerce")
age_med=df["age"].median()
df["age"]=df["age"].fillna(age_med)
df["age"]

0       37.0
1       36.0
2       55.0
3       54.0
4       27.0
        ...
1530    40.0
1531    65.0
1532    66.0
1533    45.0
1534    61.0
Name: age, Length: 1500, dtype: float64

In [565]:
# 12.The Annual Income column contains values such as 650000 INR, ₹720000,
# 1.2L, and N/A. Clean the column and convert the valid values into numeric
# format.
df["annual_income"]=pd.to_numeric(df["annual_income"],errors="coerce")

anu_med=df["annual_income"].median()
df["annual_income"]=df["annual_income"].fillna(anu_med)
df["annual_income"]

0        297809.0
1       1048283.0
2       1043481.0
3        369591.0
4        666989.0
          ...
1530     477723.0
1531    1394481.0
1532     646827.0
1533     543340.0
1534     646827.0
Name: annual_income, Length: 1500, dtype: float64

In [568]:
# 13.Clean the Credit Score column and identify values that cannot be converted
# into numbers.
df["credit_score"]=pd.to_numeric(df["credit_score"],errors="coerce")

cred_med=df["credit_score"].median()
df["credit_score"]=df["credit_score"].fillna(cred_med)
df["credit_score"]

0       698.0
1       874.0
2       661.0
3       722.0
4       727.0
        ...
1530    719.0
1531      0.0
1532    686.0
1533    720.0
1534    731.0
Name: credit_score, Length: 1500, dtype: float64

In [578]:
# 14.The Loan Amount column contains currency symbols, text, and numeric
# values. Remove the unwanted characters and convert it into numeric format.

df["loan_amount_(inr)"]=pd.to_numeric(df["loan_amount_(inr)"],errors="coerce")
df["loan_amount_(inr)"].replace({"INR":"","₹":"","$":""},inplace=True)

C:\Users\vaish\AppData\Local\Temp\ipykernel_18412\2951764116.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["loan_amount_(inr)"].replace({"INR":"","₹":"","$":""},inplace=True)

In [580]:
df["loan_amount_(inr)"]

0         378342.0
1         751792.0
2         892792.0
3         908250.0
4         386370.0
           ...
1530     1106455.0
1531      222828.0
1532    50000000.0
1533      302389.0
1534      753995.0
Name: loan_amount_(inr), Length: 1500, dtype: float64

In [582]:
# 15.The Monthly Visits column contains values such as "five", "N/A", and "-".
# Convert valid values into numeric values and handle invalid values.
import numpy as np
df["monthly_visits"].replace({"N/A":np.nan,"five":5,"-":""})
df["monthly_visits"]=pd.to_numeric(df["monthly_visits"],errors="coerce")

In [584]:
df["monthly_visits"]

0        3.0
1       11.0
2        4.0
3       10.0
4        4.0
        ...
1530     NaN
1531     8.0
1532     9.0
1533     9.0
1534     5.0
Name: monthly_visits, Length: 1500, dtype: float64

In [586]:
# 16.Clean the Debt to Income column where some values are written like 35%
# and 0.4x. Convert the valid values into a consistent numeric format.
df["debt_to_income"]=pd.to_numeric(df["debt_to_income"],errors="coerce")
df["debt_to_income"]

0       0.258
1       0.558
2         NaN
3       0.356
4       0.169
        ...
1530    0.569
1531    0.344
1532    0.084
1533    0.089
1534    0.259
Name: debt_to_income, Length: 1500, dtype: float64

In [588]:
# 17.After cleaning the numerical columns, check which columns are still stored as
# object data type.
df.select_dtypes(include=["int","float"])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1500 entries, 0 to 1534
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        1500 non-null   object
 1   age                1500 non-null   float64
 2   annual_income      1500 non-null   float64
 3   credit_score       1500 non-null   float64
 4   employment_type    1441 non-null   object
 5   education_level    1455 non-null   object
 6   marital_status     1500 non-null   object
 7   city               1448 non-null   object
 8   customer_segment   1500 non-null   object
 9   loan_type          1500 non-null   object
 10  loan_amount_(inr)  1378 non-null   float64
 11  tenure_months      1500 non-null   int64
 12  monthly_visits     1427 non-null   float64
 13  debt_to_income     1388 non-null   float64
 14  loan_approved?     1500 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 187.5+ KB

In [590]:
# Categorical Cleaning

In [592]:
# 18.Find all unique values in the Employment-Type column.
df["employment_type"].unique()

array(['Self-Employed', 'Contract', 'Salaried', ' SALARIED ',
       'Self employed', 'Business', nan, 'Unknown', 'self-employed',
       'salaried'], dtype=object)

In [594]:
# 19.Standardize the Employment-Type column so that values such as salaried,
# SALARIED, and Salaried become one consistent value.
df["employment_type"].replace({"Self employed":"Self-Employed","self-employed":"Self-Employed","salaried":"Salaried","SALARIED":"Salaried"},inplace=True)
df["employment_type"].str.strip()

C:\Users\vaish\AppData\Local\Temp\ipykernel_18412\2882284640.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["employment_type"].replace({"Self employed":"Self-Employed","self-employed":"Self-Employed","salaried":"Salaried","SALARIED":"Salaried"},inplace=True)

0       Self-Employed
1            Contract
2       Self-Employed
3            Salaried
4       Self-Employed
            ...
1530    Self-Employed
1531    Self-Employed
1532         Contract
1533         Business
1534         Salaried
Name: employment_type, Length: 1500, dtype: object

In [596]:
# 20.Clean the Education Level column and make values such as graduate,
# GRADUATE, and Graduate consistent.
df["education_level"].unique()
df["education_level"].replace({"GRADUATE":"Graduate","graduate":"Graduate","Postgraduate":"Post Graduate","postgraduate":"Post Graduate"},inplace=True)
df["education_level"].str.strip()

C:\Users\vaish\AppData\Local\Temp\ipykernel_18412\2008354557.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["education_level"].replace({"GRADUATE":"Graduate","graduate":"Graduate","Postgraduate":"Post Graduate","postgraduate":"Post Graduate"},inplace=True)

0                12th
1            Graduate
2       Post Graduate
3            Graduate
4            Graduate
            ...
1530         Graduate
1531             12th
1532            Other
1533         Graduate
1534    Post Graduate
Name: education_level, Length: 1500, dtype: object

In [598]:
# 21.Clean the City column. Identify incorrect or inconsistent values such as
# hyderbad, Hyd, Bangalore, and Bengaluru.

df["city"].replace({"MUMBAI":"Mumbai",
                   "mumbai ":"Mumbai",
                   "hyderbad":"Hyderabad",
                   "Hyd":"Hyderabad",
                   "Bangalore":"Bengaluru",
                    " Bengaluru ":"Bengaluru"
                   },inplace=True)
df["city"].str.strip().replace(" ","")
df["city"]

C:\Users\vaish\AppData\Local\Temp\ipykernel_18412\99149424.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["city"].replace({"MUMBAI":"Mumbai",

0          Mumbai
1          Jaipur
2         Kolkata
3         Kolkata
4       Hyderabad
          ...
1530       Jaipur
1531       Jaipur
1532        Delhi
1533         Pune
1534      Chennai
Name: city, Length: 1500, dtype: object

In [600]:
df["city"].unique()

array(['Mumbai', 'Jaipur', 'Kolkata', 'Hyderabad', 'Chennai', 'Bengaluru',
       nan, 'Delhi', 'Pune'], dtype=object)

In [602]:
# 22.Find all unique values in the Customer Segment column and identify invalid
# categories.
df["customer_segment"].unique()
df["customer_segment"].replace({"mass":"Mass"," PREMIUM":"Premium","premium ":"Premium",
                               },inplace=True)
df["customer_segment"]

C:\Users\vaish\AppData\Local\Temp\ipykernel_18412\3193879874.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["customer_segment"].replace({"mass":"Mass"," PREMIUM":"Premium","premium ":"Premium",

0           Mass
1        Premium
2       Affluent
3        Premium
4           Mass
          ...
1530        Mass
1531        Mass
1532        Mass
1533        Mass
1534    Affluent
Name: customer_segment, Length: 1500, dtype: object

In [604]:
df["customer_segment"].unique()

array(['Mass', 'Premium', 'Affluent', 'SME', 'unknown', 'High Value'],
      dtype=object)

In [606]:
# 23.Clean the Loan Type column so that values such as personal, PERSONAL,
# and personal loan are standardized.
df["loan_type"].unique()
df["loan_type"].replace({"Home Loan":"Home ",
                        "auto ":"Auto",
                        "personal loan":"Personal ",
                         "PERSONAL":"Personal",
                         "Personal ":"Personal",
                         "Home ":"Home"
                        },inplace=True)
df["loan_type"].str.strip()

C:\Users\vaish\AppData\Local\Temp\ipykernel_18412\4138904493.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["loan_type"].replace({"Home Loan":"Home ",

0       Education
1            Auto
2            Auto
3            Home
4       Education
          ...
1530         Home
1531     Personal
1532     Personal
1533    Education
1534    Education
Name: loan_type, Length: 1500, dtype: object

In [608]:
df["loan_type"].unique()

array(['Education', 'Auto', 'Home', 'Personal', 'Business', 'Personal ',
       'Home ', 'Unknown'], dtype=object)

In [610]:
# 24.Clean the Loan Approved column where values include Yes, yes, Y, 1, No,
# NO, N, and 0. Convert them into only Yes/No.
df["loan_approved?"].unique()
df["loan_approved?"].replace({"0":"No",
                             "N":"No",
                              "NO":"No",
                              "yes":"Yes",
                              "1":"Yes",
                              "Y":"Yes"
                             },inplace=True)

C:\Users\vaish\AppData\Local\Temp\ipykernel_18412\1669101725.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["loan_approved?"].replace({"0":"No",

In [612]:
df["loan_approved?"].unique()

array(['No', 'Yes', 'pending', 'approved'], dtype=object)

### Outliers & Data Validation

In [615]:
# 25.Check the Age column and identify unrealistic ages such as negative ages or
# ages above 100.
df["age"]=["Unrealistic Age" if i<0 or i>100 else i for i in df["age"]]
df["age"]

0       37.0
1       36.0
2       55.0
3       54.0
4       27.0
        ...
1530    40.0
1531    65.0
1532    66.0
1533    45.0
1534    61.0
Name: age, Length: 1500, dtype: object

In [617]:
# 26.Check the Credit Score column and identify values outside the valid credit-
# score range.
df["credit_score"]=["Invalid Range" if i<300 or i>900 else i for i in df["credit_score"]]
df["credit_score"]

0               698.0
1               874.0
2               661.0
3               722.0
4               727.0
            ...
1530            719.0
1531    Invalid Range
1532            686.0
1533            720.0
1534            731.0
Name: credit_score, Length: 1500, dtype: object

In [619]:
# 27.Detect outliers in Annual Income using the IQR method.
df["annual_income"]=pd.to_numeric(df["annual_income"],errors="coerce")
q1=df["annual_income"].quantile(0.25)
q3=df["annual_income"].quantile(0.75)
IQR=q3-q1
df[(df["annual_income"]<(q1-1.5*IQR)) | (df["annual_income"] > (q3+1.5*IQR))]

,customer_id,age,annual_income,credit_score,employment_type,education_level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?
14,CUST101158,60.0,1548824.0,698.0,Contract,Graduate,Married,Pune,SME,Home,333121.0,24,10.0,0.529,No
18,CUST100050,57.0,1457160.0,687.0,Business,12th,Divorced,Kolkata,Affluent,Home,258267.0,12,4.0,NaN,Yes
19,CUST100241,27.0,1412437.0,637.0,Business,Post Graduate,Married,Mumbai,Affluent,Education,752049.0,48,4.0,0.386,Yes
61,CUST100757,55.0,1777657.0,666.0,Contract,Post Graduate,Single,Hyderabad,Premium,Education,900253.0,72,3.0,0.304,Yes
74,CUST100238,41.0,1907548.0,678.0,Business,Graduate,Single,Mumbai,Mass,Business,242378.0,72,0.0,NaN,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1466,CUST100206,33.0,1604257.0,785.0,Contract,12th,Single,Mumbai,Affluent,Business,NaN,24,3.0,0.355,No
1467,CUST100035,62.0,1531271.0,779.0,Business,Post Graduate,Single,Hyderabad,Mass,Personal,327941.0,24,4.0,0.179,Yes
1511,CUST101216,26.0,1403890.0,716.0,NaN,Graduate,Single,Pune,Mass,Home,328004.0,72,6.0,0.050,approved
1515,CUST100344,45.0,80000000.0,819.0,Self-Employed,Post Graduate,Single,Mumbai,Mass,Personal,636933.0,12,6.0,0.384,Yes
1531,CUST101295,65.0,1394481.0,Invalid Range,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes

In [621]:
# 28.Detect outliers in Loan Amount using the IQR method.
df["loan_amount_(inr)"]=pd.to_numeric(df["loan_amount_(inr)"],errors="coerce")
q1=df["loan_amount_(inr)"].quantile(0.25)
q3=df["loan_amount_(inr)"].quantile(0.75)
IQR=q3-q1
df[(df["loan_amount_(inr)"]<(q1-1.5*IQR)) | (df["loan_amount_(inr)"]>(q3+1.5*IQR))]

,customer_id,age,annual_income,credit_score,employment_type,education_level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?
11,CUST100679,45.0,856826.0,662.0,Self-Employed,Post Graduate,Divorced,NaN,Affluent,Education,1412363.0,12,5.0,0.487,Yes
25,CUST100071,58.0,454340.0,743.0,Business,Graduate,Single,Jaipur,Premium,Business,1545154.0,72,3.0,0.333,Yes
58,CUST100345,63.0,477076.0,785.0,SALARIED,Graduate,MARRIED,Chennai,SME,Education,1575763.0,24,8.0,0.419,No
157,CUST101362,24.0,782709.0,842.0,Salaried,12th,Married,NaN,Premium,Personal,120000000.0,48,6.0,NaN,No
180,CUST100421,64.0,1483255.0,751.0,Contract,Post Graduate,Married,Hyderabad,Mass,Auto,2033263.0,72,3.0,0.134,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1392,CUST101039,41.0,396322.0,661.0,Self-Employed,Post Graduate,Single,Kolkata,Affluent,Education,1550762.0,84,4.0,0.337,No
1439,CUST100764,64.0,761542.0,731.0,NaN,Graduate,MARRIED,Bengaluru,Mass,Auto,2170814.0,72,2.0,0.247,Yes
1469,CUST100509,33.0,850268.0,829.0,Business,NaN,Married,Kolkata,Mass,Personal,1647932.0,72,4.0,0.329,Yes
1501,CUST100475,50.0,646827.0,802.0,Contract,12th,Divorced,Kolkata,Mass,Personal,1488587.0,36,5.0,0.023,Yes
1532,CUST100861,66.0,646827.0,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000.0,36,9.0,0.084,Yes

In [623]:
# 29.Check the Debt to Income column and identify impossible values such as
# negative values or values greater than 1.
df["debt_to_income"]=pd.to_numeric(df["debt_to_income"],errors="coerce")
df["debt_to_income"]=["Impossible value" if i<0 or i>1 else i for i in df["debt_to_income"]]
df["debt_to_income"]

0       0.258
1       0.558
2         NaN
3       0.356
4       0.169
        ...
1530    0.569
1531    0.344
1532    0.084
1533    0.089
1534    0.259
Name: debt_to_income, Length: 1500, dtype: object

In [625]:
# 30.Final cleaning task: Create a completely cleaned version of the dataset by:
# • Cleaning column names
# • Removing duplicates
# • Handling missing values
# • Fixing data types
# • Cleaning numerical columns
# • Standardizing categorical values
# • Handling invalid values
# • Detecting and treating outliers
# • Checking the final dataset for remaining errors
df.columns.str.replace("?","").str.strip()

Index(['customer_id', 'age', 'annual_income', 'credit_score',
       'employment_type', 'education_level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'loan_amount_(inr)', 'tenure_months',
       'monthly_visits', 'debt_to_income', 'loan_approved'],
      dtype='object')

In [627]:
# • Removing duplicates
df.duplicated().sum()

0

In [629]:
# • Handling missing values
df.isnull().sum()

customer_id            0
age                    0
annual_income          0
credit_score           0
employment_type       59
education_level       45
marital_status         0
city                  52
customer_segment       0
loan_type              0
loan_amount_(inr)    122
tenure_months          0
monthly_visits        73
debt_to_income       112
loan_approved?         0
dtype: int64

In [631]:
# Fixing data types
df.dtypes

customer_id           object
age                   object
annual_income        float64
credit_score          object
employment_type       object
education_level       object
marital_status        object
city                  object
customer_segment      object
loan_type             object
loan_amount_(inr)    float64
tenure_months          int64
monthly_visits       float64
debt_to_income        object
loan_approved?        object
dtype: object

In [637]:
df.to_csv("Cleaned_messy_customer_loan_dataset.csv")