In [152]:
# Easy Level (1–10)
# Q1
# Load the dataset and display the first 10 records.
import pandas as pd
import numpy as np
df=pd.read_csv("C:\\Users\\vaish\\Downloads\\Bank_customer_churn.csv")

df1=pd.read_csv("C:\\Users\\vaish\\Downloads\\Bank_customer_churn.csv")

In [2]:
# Q2
# Display the last 15 customers.
df.head(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0

In [3]:
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
5008,5009,15768359,Akhtar,534,France,Male,36,4,120037.96,1,1,0,36275.94,0
6772,6773,15652700,Ritchie,539,France,Male,39,6,0.00,2,1,1,86767.48,0
3720,3721,15788775,Milne,473,Germany,Male,40,8,152576.25,2,1,0,73073.68,0
3612,3613,15792151,Hamilton,635,Spain,Female,37,3,0.00,2,1,0,91086.73,0
449,450,15658169,Cook,778,Spain,Female,47,6,127299.34,2,1,0,124694.99,0
3242,3243,15729908,Allan,411,France,Female,36,10,0.00,1,0,0,120694.35,0
8792,8793,15766137,Muir,497,France,Male,34,2,0.00,2,1,1,83087.13,0

In [7]:
# Q4
# Print complete dataset information and identify:
# • Total columns
# • Data type of each column
# • Missing values

df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [9]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [11]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [13]:
# Q5
# Find missing values in every column.
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [17]:
# Q6
# Display only numerical columns.
df.select_dtypes(include = ["int64"]).columns

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'Exited'],
      dtype='object')

In [19]:
# Q7
# Generate the statistical summary of numerical columns.
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [21]:
# Q8
# Find duplicate rows and print how many exist.
df.duplicated().sum()

0

In [23]:
# Q9
# Remove duplicate rows and store the cleaned dataset.
df.drop_duplicates(inplace=True)

In [25]:
# Q10
# Count how many customers have exited and how many have not exited.
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [27]:
# Medium Level (11–20)
# Q11
# Rename the following columns:
# CustomerId → Customer_ID
#  CreditScore→ Credit_Score
# EstimatedSalary → Salary
# Exited → ChurnMedium Level (11–20)
# Q11
# Rename the following columns:
# CustomerId → Customer_ID
# CreditScore → Credit_Score
# EstimatedSalary → Salary
# Exited → Churn
df.rename(columns={"CustomerId":"Customer_ID","CreditScore":"Credit_Score","EstimatedSalary":"Salary"},inplace=True)
df.columns

Index(['RowNumber', 'Customer_ID', 'Surname', 'Credit_Score', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'Salary', 'Exited'],
      dtype='object')

In [29]:
# Q12
# Add the prefix
# Bank_
# to every column name.
df=df.add_prefix("Bank_")
df.columns

Index(['Bank_RowNumber', 'Bank_Customer_ID', 'Bank_Surname',
       'Bank_Credit_Score', 'Bank_Geography', 'Bank_Gender', 'Bank_Age',
       'Bank_Tenure', 'Bank_Balance', 'Bank_NumOfProducts', 'Bank_HasCrCard',
       'Bank_IsActiveMember', 'Bank_Salary', 'Bank_Exited'],
      dtype='object')

In [37]:
# Q13
# Convert the Age column into float datatype.
df["Age"]=df["Age"].astype("float")
df["Age"]

0       42.0
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Age, Length: 10000, dtype: float64

In [39]:
# Q14
# Convert the Exited column into string datatype.
df["Exited"]=df["Exited"].astype("str")
df["Exited"]

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: object

In [47]:
# Q15
# Suppose the Balance column has missing values.
# Replace them using the mean of the Balance column.
bal_mean=int(df["Balance"].mean())
bal_mean
rep_bal=df["Balance"].fillna("bal_mean")
rep_bal

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [53]:
# Q16
# Suppose the Age column has missing values.
# Replace them using the median age.
age_median=df["Age"].median()
age_median
rep_age=df["Age"].fillna("Age")
rep_age

0       42.0
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Age, Length: 10000, dtype: float64

In [59]:
# Q17
# Display only the first five rows after renaming the columns.
df.rename(columns={"CustomerId":"Customer_ID","CreditScore":"Credit_Score","EstimatedSalary":"Salary"},inplace=True)
df
df.head()

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [69]:
# Q18
# Create a new DataFrame by dropping these columns:
# RowNumber
# CustomerId
# Surname
# Display the first 10 rows.
new_df=df.drop(["RowNumber","Customer_ID","Surname"],axis=1)
new_df.head(10)

,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Exited
0,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
5,645,Spain,Male,44.0,8,113755.78,2,1,0,149756.71,1
6,822,France,Male,50.0,7,0.00,2,1,1,10062.80,0
7,376,Germany,Female,29.0,4,115046.74,4,1,0,119346.88,1
8,501,France,Male,44.0,4,142051.07,2,0,1,74940.50,0
9,684,France,Male,27.0,2,134603.88,1,1,1,71725.73,0

In [71]:
# Q19
# Drop the Geography column and display dataset information again.
geo_drop=df.drop("Geography",axis=1)
geo_drop

,RowNumber,Customer_ID,Surname,Credit_Score,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Exited
0,1,15634602,Hargrave,619,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [73]:
# Q20
# Rename NumOfProducts to Products and HasCrCard to CreditCard.
rename=df.rename({"NumOfProducts":"Products","HasCrCard":"CreditCard"})
rename

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

#### Hard Level (21–30)

In [78]:
# Q21 (Real Company Task)
# Your manager wants cleaner column names.
# Rename every column as follows:
# RowNumber → Row_No
# CustomerId → Customer_ID
# Surname → Last_Name
# CreditScore → Credit_Score
# Geography → Country
# Gender → Sex
# EstimatedSalary → Salary
# Exited → Target
# Display the first five rows.
rename_all=df1.rename({"RowNumber":"Row_No","CustomerId":"Customer_ID","Surname":"Last_Name","CreditScore":"Credit_Score","Geography":"Country","Gender":"sex","EstimatedSalary":"Salary","Exited":"Target"})
rename_all

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [82]:
# Q22
# Create a new DataFrame that contains only numeric columns.
# Then generate its statistical summary.
Stat_summary=df1.describe()
Stat_summary

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [90]:
# Q23
# Your company received duplicate customer records.
# Tasks:
# • Count duplicates.
# • Remove duplicates.
# • Display dataset information after cleaning.
df1.duplicated().sum()

0

In [94]:
df1.drop_duplicates()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [100]:
# Q24
# Management wants every column name to begin with
# Customer_
# Apply this transformation using the appropriate method.
suff_df1=df1.add_prefix("Customer_")
suff_df1

,Customer_RowNumber,Customer_CustomerId,Customer_Surname,Customer_CreditScore,Customer_Geography,Customer_Gender,Customer_Age,Customer_Tenure,Customer_Balance,Customer_NumOfProducts,Customer_HasCrCard,Customer_IsActiveMember,Customer_EstimatedSalary,Customer_Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [112]:
# Q25
# After renaming the columns, convert
# Age
# Balance
# Salary
# to float datatype.
# Print dataset information.
select_float=df.select_dtypes(include=["float"]).columns
for col in select_float:
    df[col]=df[col].astype("float")
select_float

Index(['Balance', 'EstimatedSalary'], dtype='object')

In [116]:
# Q26
# Assume CreditScore contains missing values.
# Replace them with the median CreditScore.
credit_median=df1["CreditScore"].median()
credit_median
df1["CreditScore"]=df1['CreditScore'].fillna(credit_median)
df1["CreditScore"]

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [118]:
# Q27
# Assume EstimatedSalary contains missing values.
# Replace them with the mean salary.
# Then print the first eight rows.
est_mean=df["EstimatedSalary"].mean()
est_mean
df1["EstimatedSalary"]=df1["EstimatedSalary"].fillna(est_mean)
df1["EstimatedSalary"]
df1.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

In [154]:
# Q28 (Data Cleaning Challenge)
# Perform all the following:
# • Remove duplicate rows.
# • Rename Exited to Target.
# • Convert Target to string.
# • Display dataset information.
dup=df1.duplicated().sum()
dup
df1.rename({"Exited":"Target"})
df1

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [160]:
convert=ren["Exited"].astype("str")
convert

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: object

In [162]:
df_info=df1.info()
df_info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [166]:
# Q29 (Transformation Challenge)
# Create a copy of the dataset.
# Perform these transformations:
# • Rename Gender to CustomerGender
# • Rename Geography to Country
# • Add prefix Bank_
# • Remove RowNumber
# • Display first 10 rows
df2=pd.read_csv("C:\\Users\\vaish\\Downloads\\Bank_customer_churn.csv")
df2

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [168]:
rename=df2.rename({"Gender":"CustomerGender","Geography":"Country"})
rename

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [170]:
pre=df2.add_prefix("Bank_")
pre.columns

Index(['Bank_RowNumber', 'Bank_CustomerId', 'Bank_Surname', 'Bank_CreditScore',
       'Bank_Geography', 'Bank_Gender', 'Bank_Age', 'Bank_Tenure',
       'Bank_Balance', 'Bank_NumOfProducts', 'Bank_HasCrCard',
       'Bank_IsActiveMember', 'Bank_EstimatedSalary', 'Bank_Exited'],
      dtype='object')

In [174]:
drop=df2.drop("RowNumber",axis=1)
drop

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [176]:
df2.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [182]:
# Q30 Real Industry Mini Project
# Your manager asks you to prepare a cleaned dataset for the Machine Learning team.
# Perform all of these steps:
# 1. Load the dataset.
# 2. Display dataset information.
# 3. Check missing values.
# 4. Remove duplicate rows.
# 5. Rename the following columns:
# o CustomerId → Customer_ID
# o CreditScore → Credit_Score
# o EstimatedSalary → Salary
# o Exited → Target
# 6. Convert:
# o Age → float
# o Balance → float
# o Target → string
# 7. Replace missing values:
# o Age → median
# o Balance → mean
# 8. Remove:
# o RowNumber
# o Surname
# 9. Display:
# o First 10 rows
# o Statistical summary
# o Value counts of Target
# o Final dataset information
df3=pd.read_csv("C:\\Users\\vaish\\Downloads\\Bank_customer_churn.csv") 
df3

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [184]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [190]:
null=df3.isna().sum()
null

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [194]:
dup_rows=df3.drop_duplicates()
dup_rows

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [226]:
df3.rename(columns={"CustomerId":"Customer_ID","CreditScore":"Credit_Score","EstimatedSalary":"Salary","Exited":"Target"},inplace=True)
df3.columns

Index(['RowNumber', 'Customer_ID', 'Surname', 'Credit_Score', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'Salary', 'Target'],
      dtype='object')

In [228]:
age=df3["Age"].astype("float")
age
bal=df3["Balance"].astype("float")
bal
tar=df3["Target"].astype("str")
tar

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Target, Length: 10000, dtype: object

In [230]:
age_median=df3["Age"].median()
age_median
df3["Age"]=df3["Age"].fillna(age_median)
df3["Age"]

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

In [232]:
bal_mean=df3["Balance"].mean()
bal_mean
df3["Balance"]=df3["Balance"].fillna(bal_mean)
df3["Balance"]

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [234]:
df3.drop("RowNumber",axis=1)

,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [236]:
df3.drop("Surname",axis=1)

,RowNumber,Customer_ID,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [238]:
df3.head(10)

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [240]:
df3.describe

<bound method NDFrame.describe of       RowNumber  Customer_ID    Surname  Credit_Score Geography  Gender  Age  \
0             1     15634602   Hargrave           619    France  Female   42
1             2     15647311       Hill           608     Spain  Female   41
2             3     15619304       Onio           502    France  Female   42
3             4     15701354       Boni           699    France  Female   39
4             5     15737888   Mitchell           850     Spain  Female   43
...         ...          ...        ...           ...       ...     ...  ...
9995       9996     15606229   Obijiaku           771    France    Male   39
9996       9997     15569892  Johnstone           516    France    Male   35
9997       9998     15584532        Liu           709    France  Female   36
9998       9999     15682355  Sabbatini           772   Germany    Male   42
9999      10000     15628319     Walker           792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember     Salary  \
0          2       0.00              1          1               1  101348.88
1          1   83807.86              1          0               1  112542.58
2          8  159660.80              3          1               0  113931.57
3          1       0.00              2          0               0   93826.63
4          2  125510.82              1          1               1   79084.10
...      ...        ...            ...        ...             ...        ...
9995       5       0.00              2          1               0   96270.64
9996      10   57369.61              1          1               1  101699.77
9997       7       0.00              1          0               1   42085.58
9998       3   75075.31              2          1               0   92888.52
9999       4  130142.79              1          1               0   38190.78

      Target
0          1
1          0
2          1
3          0
4          0
...      ...
9995       0
9996       0
9997       1
9998       1
9999       0

[10000 rows x 14 columns]>

In [242]:
df3["Target"].value_counts(dropna=False)

Target
0    7963
1    2037
Name: count, dtype: int64

In [244]:
df3.info

<bound method DataFrame.info of       RowNumber  Customer_ID    Surname  Credit_Score Geography  Gender  Age  \
0             1     15634602   Hargrave           619    France  Female   42
1             2     15647311       Hill           608     Spain  Female   41
2             3     15619304       Onio           502    France  Female   42
3             4     15701354       Boni           699    France  Female   39
4             5     15737888   Mitchell           850     Spain  Female   43
...         ...          ...        ...           ...       ...     ...  ...
9995       9996     15606229   Obijiaku           771    France    Male   39
9996       9997     15569892  Johnstone           516    France    Male   35
9997       9998     15584532        Liu           709    France  Female   36
9998       9999     15682355  Sabbatini           772   Germany    Male   42
9999      10000     15628319     Walker           792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember     Salary  \
0          2       0.00              1          1               1  101348.88
1          1   83807.86              1          0               1  112542.58
2          8  159660.80              3          1               0  113931.57
3          1       0.00              2          0               0   93826.63
4          2  125510.82              1          1               1   79084.10
...      ...        ...            ...        ...             ...        ...
9995       5       0.00              2          1               0   96270.64
9996      10   57369.61              1          1               1  101699.77
9997       7       0.00              1          0               1   42085.58
9998       3   75075.31              2          1               0   92888.52
9999       4  130142.79              1          1               0   38190.78

      Target
0          1
1          0
2          1
3          0
4          0
...      ...
9995       0
9996       0
9997       1
9998       1
9999       0

[10000 rows x 14 columns]>

#### Bonus Challenge (Create New Columns)

In [265]:
# Create a new column:
# TotalMoney = Balance + EstimatedSalary
df4=pd.read_csv("C:\\Users\\vaish\\Downloads\\Bank_customer_churn.csv")
df4["TotalMoney"]=df4["Balance"]+df4["EstimatedSalary"]
df4

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,TotalMoney
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,101348.88
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,196350.44
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,273592.37
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,93826.63
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,204594.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,96270.64
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,159069.38
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,42085.58
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,167963.83
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,168333.57

In [271]:
# B2
# Create a new column:
# DoubleScore = CreditScore × 2
cred_2=df4["DoubleScore"]=df4["CreditScore"]*2
cred_2

0       1238
1       1216
2       1004
3       1398
4       1700
        ...
9995    1542
9996    1032
9997    1418
9998    1544
9999    1584
Name: CreditScore, Length: 10000, dtype: int64

In [273]:
# Create a new column:
# AgeAfter10Years = Age + 10
add_10=df4["AgeAfter10Years"]=df4["Age"]+10
add_10

0       52
1       51
2       52
3       49
4       53
        ..
9995    49
9996    45
9997    46
9998    52
9999    38
Name: Age, Length: 10000, dtype: int64

In [275]:
# B4
# Create a new column:
# HasBalance = Balance
# Replace missing values in this new column using the mean.
bal=df4["HasBalance"]=df4["Balance"]
bal

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [279]:
bal_mean=df4["HasBalance"].mean()
bal_mean
df4["HasBalance"]=df4["HasBalance"].fillna(bal_mean)
df4["HasBalance"]

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: HasBalance, Length: 10000, dtype: float64

In [281]:
# Create a new column:
# SalaryInLakhs = EstimatedSalary / 100000
sal_lakh=df4["SalaryInLakhs"]=df4["EstimatedSalary"]/100000
sal_lakh

0       1.013489
1       1.125426
2       1.139316
3       0.938266
4       0.790841
          ...
9995    0.962706
9996    1.016998
9997    0.420856
9998    0.928885
9999    0.381908
Name: EstimatedSalary, Length: 10000, dtype: float64