In [6]:
# 1. Load the dataset using the appropriate Pandas method and store it in a
# variable named df.
import pandas as pd
df=pd.read_csv("C:\\Users\\vaish\\Downloads\\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [14]:
# 2. Display the first 8 rows of the dataset.
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

In [16]:
# 3. Display the last 12 rows of the dataset.
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [18]:
# 4. Show 10 random rows from the dataset.
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3327,3328,15659325,Todd,802,Spain,Male,40,5,0.00,2,1,1,175043.69,0
3870,3871,15746341,Ejikemeifeuwa,630,France,Male,40,8,0.00,2,1,1,42495.81,0
1488,1489,15625824,Kornilova,596,Spain,Male,30,6,121345.88,4,1,0,41921.75,1
8382,8383,15612594,Ifeanacho,599,Spain,Male,25,3,0.00,2,1,1,120790.02,0
1205,1206,15724307,Mitchell,780,France,Male,76,10,121313.88,1,0,1,64872.33,0
4813,4814,15723858,Schiavone,517,Spain,Male,39,3,0.00,2,0,1,12465.51,0
6035,6036,15764021,Frolov,617,France,Male,34,1,61687.33,2,1,0,105965.25,0
6021,6022,15579891,Milani,714,France,Male,52,4,100755.66,1,1,1,186775.25,0
4239,4240,15756481,Garcia,636,France,Female,39,3,118336.14,1,1,0,184691.77,0
3785,3786,15803842,Dunn,752,Germany,Female,45,3,105426.50,2,0,1,89773.45,0

In [22]:
# # 5. Find the shape of the dataset.
# o How many rows are there?
# o How many columns are there?
df.shape

(10000, 14)

In [26]:
# 6. Display complete information about the dataset using one method.
# o Number of non-null values
# o Data types
# o Memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [30]:
# 7. Print the names of all columns in the dataset.
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [36]:
# 8. Find the data type of every column.
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [38]:
# 9. Check for missing values in every column using:
# o isnull().sum()
# o isna().sum()
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [40]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [48]:
# 10.Select only one column:
# o CreditScore
Credit=df["CreditScore"]
Credit

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [50]:
# 11.Select the following multiple columns:
# o CustomerId
# o Surname
# o Balance
# o Exited
df[["CustomerId","Surname","Balance","Exited"]]

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

In [64]:
# 12.Display only numeric columns using select_dtypes().
df.select_dtypes(include=["int64"]).columns

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'Exited'],
      dtype='object')

In [66]:
# 13.Generate the statistical summary of all numeric columns using describe().
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [68]:
# 14.Check for duplicate rows in the dataset.
# o How many duplicate rows exist?

# o Remove all duplicate rows.
df.duplicated().sum

<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool>

In [76]:
df.drop_duplicates(inplace=True)

In [82]:
# 15.Count the number of customers in each class of the Exited column using
# value_counts().
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

#### Operators + Loops (1-5)

In [90]:
# 1. Take two numbers from user. Perform all arithmetic operations and also check
# which number is greater using comparison operators.
num1=int(input("Enter the number"))
num2=int(input("Enter the number"))
print("Addition= ",num1+num2)
print("Substraction= ",num1-num2)
print("Multiplication= ",num1*num2)
print("Division= ",num1/num2)
print("Floor Division= ",num1//num2)

if num1>num2:
    print("Number 1 id greatest")
else:
    print("Number 2 is greatest")

Enter the number 56
Enter the number 45

Addition=  101
Substraction=  11
Multiplication=  2520
Division=  1.2444444444444445
Floor Division=  1
Number 1 id greatest

In [117]:
# 2. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop
# completely when number 40 is reached using break.
for i in range (1,51):
    if i==40:
        break
    if i%5==0:
        continue
    
    print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39

In [119]:
# 3. Take numbers from user until they enter negative number. Calculate sum and
# average using while loop.

total=0
count=0
while True:
    num=int(input("Enter a number: "))
    if num<0:
        break
    total+=num
    count+=1
if count>0:
    average=total/count
    print("Sum= ",total)
    print("Average= ",average)
else:
    print("negative numer enetred")

In [127]:
# 4. Print the following pattern using nested loops:
# *****
# ****
# ***
# **
# *
for i  in range(5,0,-1):
    for j in range(i):
        
        print("*",end="")
    print()

*****
****
***
**
*

In [133]:
# 5. Find the factorial of a number using for loop and also using while loop.
num=int(input("Enter a number"))
fact=1

for i in range(1,num+1):
    fact=fact*i

print("Factorial= ",fact)

Enter a number 6

Factorial=  720

#### Data Types & Methods (6-9)

In [146]:
# 6. Take a string and perform: convert to uppercase, count occurrences of ‘a’, replace
# spaces with -, and check if it starts with “Hello”.
string="Hello, This is python"
print("Uppercase= ",string.upper())
print(string.count('a'))
print(string.replace(" ",'-'))
print(string.startswith("Hello"))

Uppercase=  HELLO, THIS IS PYTHON
0
Hello,-This-is-python
True

In [162]:
# 7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending)
# and reverse.
lis=[12,3,4,5,6]
lis.append(34)
print(lis)
lis.insert(2,34)
print(lis)
lis.remove(12)
print(lis)
lis.pop()
print(lis)
lis.sort()
print(lis)
lis.reverse()
print(lis)

[12, 3, 4, 5, 6, 34]
[12, 3, 34, 4, 5, 6, 34]
[3, 34, 4, 5, 6, 34]
[3, 34, 4, 5, 6]
[3, 4, 5, 6, 34]
[34, 6, 5, 4, 3]

In [172]:
# 8. Create a dictionary of 4 students (name:marks). Print only those students who
# scored more than 80 using items().
dict1={"Vaishnavi":99,"Shivani":76,"Pallavi":98,"Ram":34}

for name,marks in dict1.items():
    if marks>80:
        print(name,":",marks)

Vaishnavi : 99
Pallavi : 98

In [180]:
# 9. Create two sets and perform union, intersection, difference. Also add and discard
# elements.
set1={1,2,3,4,5}
set2={5,6,7,8,9}
print("Union",set1.union(set2))
print("intersection",set1.intersection(set2))
print("difference",set1.difference(set2))

Union {1, 2, 3, 4, 5, 6, 7, 8, 9}
intersection {5}
difference {1, 2, 3, 4}

#### OOP + Encapsulation (10-14)

In [185]:
# 10. Create a class Student with private attribute __marks. Add getter and setter with
# validation (0–100).
class Student:
    def __init__(self,marks):
        self.__marks=marks
    def get_marks(self):
        return f"The marks are = {self.__marks}"
    def set_marks(self,new):
        if 0<new<100:
            print("Updated marks are= ",new)
        else:
            print("Enter valid marks")

std=Student(67)
std.get_marks()
std.set_marks(89)

Updated marks are=  89

In [189]:
# 11. Create class BankAccount with private __balance. Add deposit and withdraw
# methods. Raise custom exception if balance becomes negative.
class NegativeValueError(Exception):
    pass
class BankAccount:
    def __init__(self,balance):
        self.__balance=balance
    def get_marks(self):
        return f"The Balance are = {self.__balance}"
    def set_marks(self,new):
        if new>=0:
            self.__balance+=new
            print("Updated balance = ",self.__balance)
        else:
            raise NegativeValueError("Entered negative value")
    def deposit(self,amt):
        if amt>=0:
            self.__balance+=amt
            print("The amount after deposited is= ",self.__balance)
        else:
            raise NegativeValueError("Entered negative value")
    def withdraw(self,with_amt):
        if with_amt>=0:
            self.__balance-=with_amt
            print("The amount after withdrawn is= ",self.__balance)
        else:
            raise NegativeValueError("Entered negative value")

try:
    b1=BankAccount(50000)
    print("Current Balance =",b1.get_marks())
    b1.deposit(200)
    b1.withdraw(3000)
    b1.withdraw(4000)
except NegativeValueError as e:
    print(e)

Current Balance = The Balance are = 50000
The amount after deposited is=  50200
The amount after withdrawn is=  47200
The amount after withdrawn is=  43200

In [195]:
# 12. Create class Employee with class attribute company_name. Show that it is
# shared by all objects. Also update the class attribute.
class Employee:
    company_name="Google"
    def show(self,name):
        self.name=name
        print("Name= ",self.name)
        print("Company = ",Employee.company_name)
emp1=Employee()
emp2=Employee()
emp1.show('Vaishnavi')
emp2.show("Mangesh")

Name=  Vaishnavi
Company =  Google
Name=  Mangesh
Company =  Google

In [201]:
# 13. Create class Product with private __price. Add getter and setter. Setter should
# not allow price less than 100.
class Product:
    def __init__(self,price):
        self.__price=price
    def get_price(self):
        return f"The price is {self.__price}"
    def set_price(self,new):
        if new<100:
            print("Invalid Enter value more than 100")
        else:
            self.__price+=new
            print("The updated price is = ", self.__price)
prd=Product(34)
prd.set_price(1)

Invalid

In [205]:
# 14. Create class Rectangle with private length and width. Add method to calculate
# area and perimeter.
class Rectangle:
    def __init__(self,l,w):
        self.__l=l
        self.__w=w
    def set_len(self):
        return self.__l
    def set_wid(self):
        return self.__w
    def calc_area(self):
        area=self.__l+self.__w
        print("Area= ",area)
    def calc_peri(self):
        perimeter=2*(self.__l+self.__w)
        print("Perimeter= ",perimeter)
rect=Rectangle(4,5)
rect.calc_area()
rect.calc_peri()

Area=  9
Perimeter=  18

#### Inheritance + Abstraction + super() (15-19)

In [208]:
# 15. Create single level inheritance: Person → Student. Use super() in constructor.
class Person:
    def __init__(self,name):
        self.name=name
class Student(Person):
    def __init__(self,name,marks):
        super().__init__(name)
        self.marks=marks
    def display(self):
        print("Name= ",self.name)
        print("Marks= ",self.marks)
std=Student("Vaishnavi","99")
std.display()

Name=  Vaishnavi
Marks=  99

In [216]:
# 16. Create multi-level inheritance: Person → Employee → Manager. Override a
# method at each level.
class Person:
    def __init__(self,name,**kwargs):
        super().__init__(**kwargs)
        self.name=name
class Employee(Person):
    def __init__(self,name,em_id,**kwargs):

        super().__init__(name,**kwargs)
        self.em_id=em_id 
class Manager(Employee):
    def __init__(self,name,em_id,salary):
        super().__init__(name,em_id)
        self.salary=salary
    def display(self):
        print("Name= ",self.name)
        print("Em_id= ",self.em_id)
        print("Salary= ",self.salary)
man=Manager("Vaishnavi","Emp123",20000000)
man.display()

Name=  Vaishnavi
Em_id=  Emp123
Salary=  20000000

In [218]:
# 17. Create hierarchical inheritance: Parent Animal → Dog and Cat. Override sound()
# method.
class Animal:
    def sound(self):
        print("Animal make sound")
class Dog(Animal):
    def sound(self):
        print("Dog barks")
class Cat(Animal):
    def sound(self):
        print("Cat Meows")
d=Dog()
c=Cat()
d.sound()
c.sound()

Dog barks
Cat Meows

In [226]:
# 18. Create abstract class Shape with abstract method area(). Implement it in Circle
# and Square using super().
from abc import ABC,abstractmethod
class Shape(ABC):
    def __init__(self,value):
        self.value=value
        
    @abstractmethod
    def area(self):
        pass
class Circle(Shape):
    def __init__(self,r):
        super().__init__(r)
    def area(self):
        area=3.14*self.value**2
        print("Area= ",area)
class Square(Shape):
    def __init__(self,s):
        super().__init__(s)
    def area(self):
        area=self.value**2
        print('Area= ',area)

c=Circle(34)
s=Square(6)
c.area()
s.area()

Area=  3629.84
Area=  36

In [263]:
# 19. Create multiple inheritance with two classes Father and Mother. Create child
# class and resolve method conflict.
class Father:
    def show(self):
        print("This is Father's method.")
class Mother:
    def show(self):
        print("This is Mother's method.")
class Child(Father, Mother):
    def show(self):
        print("This is Child's method.")
        Father.show(self)   
        Mother.show(self)   
c = Child()
c.show()

This is Child's method.
This is Father's method.
This is Mother's method.

##### overloading + Exception + File Handling (20-25)

In [233]:
# 20. Create a class Calculator that can add 2 or 3 numbers (method overloading
# using *args).    
class Calculator:
    def add (self,a,b,c=0,d=0):
        return a+b+c+d
cal=Calculator()
cal.add(1,2)

3

In [239]:
# 21. Create class Point and overload + and > operators.
class Point:
    def __init__(self,a):
        self.a=a
    def __add__(self,other):
        return self.a+other.a
    def __gt__(self,other):
        return self.a>other.a
p1=Point(3)
p2=Point(4)
print(p1+p2)
print(p1>p2)

7
False

In [243]:
# 22. Write a program that handles ZeroDivisionError, ValueError and IndexError using
# multiple except blocks.
try:
    a=int(input("Enter a number"))
    b=int(input("Enter a number"))
    c=a/b
    print("Result= ",c)

    lst=[10,20,30]
    index=int(input("Enter the index"))
    print("Element= ",lst[index])
    
except ZeroDivisionError:
    print("Error cannot be Divided by Zero")
except ValueError:
    print("Error enter valid integer value")
except IndexError:
    print("Error Index out of range")

Enter a number 33
Enter a number 3

Result=  11.0

Enter the index 5

Error Index out of range

In [245]:
# 23. Create a custom exception InvalidAgeError. Raise it if age is less than 18.
class InvalidAgeError(Exception):
    pass
try:
    age=int(input("Enter age"))
    if age<=18:
        raise InvalidAgeError('Error age is not valid')
    else:
        print("Age= ",age)
except InvalidAgeError as e:
    print(e)

Enter age 4

Error age is not valid

In [257]:
# 24. Write a program to read a file, count number of words, and write the count into
# another file.
with open("Std.txt","r")as file:
    data=file.read()
word_count=len(data.split())

with open ("output.txt","w")as file:
    file.write(f"Word Count= {word_count}")
print("program run success")

program run success

In [261]:
# 25. Create a menu-driven program for file operations: Write, Read, Append, and Exit.
# Handle FileNotFoundError.
while True:
    print("\n----- File Menu -----")
    print("1. Write")
    print("2. Read")
    print("3. Append")
    print("4. Exit")
    choice=int(input("Enter your choice"))
    if choice==1:

        file=open("File.txt","w")
        file.write("Hey this is the File file")
    elif choice==2:
        try:
        file=open("File.txt","r")
        print(file.read())
    elif choice==3:
        file=open("File.txt","a")
        file.write("This is second line of code")
        file=open("File.txt","r")
        print(file.read())

Hey this is the File file
Hey this is the File fileThis is second line of code
This file does not exist