### Pandas Challenges (Based on Your Notebook)

In [103]:
# Challenge 1 – Complete Data Cleaning
# Your manager gives you a messy dataset.
# Perform all of the following:
# • Load the dataset.
# • Display dataset information.
# • Find missing values.
# • Remove duplicate rows.
# • Fill missing values:
# o Age → median
# o Balance → mean
# • Rename:
# o Target → CustomerStatus
# o AnnualIncome → Income
# • Display the first 15 rows.
import pandas as pd
df=pd.read_csv("C:\\Users\\vaish\\Downloads\\Task_dataset.csv")
df

df1=pd.read_csv("C:\\Users\\vaish\\Downloads\\Task_dataset.csv")
df1

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [12]:
df.isnull().sum()

 CustomerID      0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [18]:
df.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [26]:
sel_median=df["Age"].median()
sel_median
df["Age"]=df["Age"].fillna(sel_median)
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [28]:
bal_mean=df["Balance"].mean()
bal_mean
df["Balance"]=df["Balance"].fillna(bal_mean)
df["Balance"]

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [30]:
new=df.rename({"Target":"CustomerStatus","AnnualIncome":"Income"})
new

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn

In [32]:
df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,22.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

In [44]:
# Challenge 2 – Banking Report
# The bank wants a numeric report.
# Tasks
# • Select only numeric columns.
# • Display summary statistics.
# • Convert Age and CreditScore to float.
# • Display information again.
num=df.select_dtypes(include=["int"]).columns
num

Index([' CustomerID ', 'Spending', 'CreditScore', 'Tenure'], dtype='object')

In [46]:
df.describe

<bound method NDFrame.describe of        CustomerID    Age  AnnualIncome  Spending  CreditScore        Balance  \
0            10001  58.0       49184.0      2139          581   97523.535666
1            10002  65.0      162964.0      6197          732    6356.540000
2            10003  56.0       26956.0     37281          503  143203.920000
3            10004  55.0       92926.0       925          463  139627.880000
4            10005  66.0      108236.0      7198          394   75985.460000
...            ...   ...           ...       ...          ...            ...
1015         10450  43.0      173620.0      7121          644   60353.030000
1016         10753  25.0       54490.0     13794          303  124512.070000
1017         10810  49.0       82062.0     47170          813   53850.090000
1018         10267  38.0           NaN     10424          722  138100.050000
1019         10059  62.0       97504.0     36833          430   97523.535666

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]>

In [58]:
df["Age"]=df["Age"].astype("float")
df["Age"]
df["CreditScore"]=df["CreditScore"].astype("float")
df["CreditScore"]

0       581.0
1       732.0
2       503.0
3       463.0
4       394.0
        ...
1015    644.0
1016    303.0
1017    813.0
1018    722.0
1019    430.0
Name: CreditScore, Length: 1020, dtype: float64

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   float64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 87.8+ KB

In [82]:
# Challenge 3 – Duplicate Investigation
# Find duplicate customers.
# Then
# • Count duplicate rows.
# • Remove duplicates.
# • Print information before and after removing duplicates.
# • Show the last 20 rows.
dup=df.duplicated().sum()
dup

20

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [86]:
rem=df.drop_duplicates()
rem

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [90]:
df.tail(20)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1000,10643,41.0,125012.0,18825,761,35977.85,2,Germany,Other,Retail,Stay
1001,10763,56.0,102965.0,17517,838,115028.54,9,UK,NaN,SME,Stay
1002,10910,66.0,118506.0,6296,306,81892.13,4,Canada,Male,SME,Churn
1003,10200,19.0,115052.0,20741,484,190233.86,5,Canada,Male,Retail,Churn
1004,10587,29.0,NaN,40255,383,168358.60,2,Germany,Male,Corporate,Churn
1005,10798,22.0,176830.0,7626,688,65481.65,10,France,Male,Retail,Stay
1006,10653,32.0,NaN,21266,598,142086.70,9,France,Female,Corporate,Stay
1007,10756,53.0,74430.0,3705,489,29651.23,10,UK,Male,Retail,Churn
1008,10417,70.0,40417.0,37956,681,23880.19,10,India,Male,Retail,Stay
1009,10499,34.0,166546.0,12497,643,130886.93,3,UK,Male,SME,Stay
1010,10515,62.0,199762.0,41808,309,60223.29,10,India,Other,SME,Churn
1011,10457,44.0,63604.0,27633,804,176354.13,5,Germany,Female,Retail,Stay
1012,10882,61.0,115417.0,3879,413,76591.00,7,NaN,Male,Corporate,Churn
1013,10531,64.0,85162.0,32083,654,132742.13,10,Canada,Male,SME,Stay
1014,10181,50.0,166466.0,44281,662,14415.10,0,Canada,Male,Corporate,Churn
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [107]:
# Challenge 4 – HR Department
# HR wants better column names.
# Rename
# CustomerID → Employee_ID
# Age → EmployeeAge
# Gender → EmployeeGender
# AnnualIncome → Salary
# Target → PromotionStatus
# Then
# • Add prefix
# HR_
# to every column.
# Display 10 random records.
df1.rename(columns={"CustomerID":"Employee_ID","Age":"EmployeeAge","Gender":"EmployeeGender","AnnualIncome":"Salary","Target":"PromotionStatus"},inplace=True)
df1

,CustomerID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [111]:
df1.add_prefix("HR_")

,HR_ CustomerID,HR_EmployeeAge,HR_Salary,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [113]:
df1.sample(10)

,CustomerID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
772,10773,27.0,93520.0,2542,647,196723.75,10,Germany,Male,SME,Stay
862,10863,60.0,31302.0,4040,672,57012.90,6,UK,Female,SME,Stay
828,10829,61.0,67164.0,21030,860,2115.60,0,India,Male,Corporate,Churn
309,10310,44.0,129185.0,37022,842,26818.55,3,UK,Male,NaN,Stay
891,10892,59.0,108048.0,27480,892,68558.50,10,UK,Female,SME,Stay
714,10715,61.0,170999.0,6371,415,134349.51,6,UK,Female,Retail,Churn
56,10057,61.0,195801.0,13412,672,86259.48,10,UK,Other,Corporate,Stay
250,10251,26.0,117134.0,34249,875,21236.79,3,Canada,Male,Corporate,Stay
406,10407,23.0,154035.0,13816,459,107278.03,6,Germany,Other,SME,Churn
211,10212,48.0,137598.0,40827,305,181171.50,0,UK,Male,Retail,Churn

In [117]:
# Challenge 5 – Finance Cleaning
# Finance department reports missing values.
# Tasks
# Fill
# AnnualIncome → Median
# Balance → Mean
# Age → Median
# Then
# Generate descriptive statistics.
anu_median=df["AnnualIncome"].median()
anu_median
df['AnnualIncome']=df["AnnualIncome"].fillna(anu_median)
df['AnnualIncome']

0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018    112358.0
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64

In [119]:
bal_mean=df["Balance"].mean()
bal_mean
df["Balance"]=df["Balance"].fillna(bal_mean)
df["Balance"]

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [121]:
age_median=df["Age"].median()
age_median
df["Age"]=df["Age"].fillna(age_median)
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [123]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [129]:
# Challenge 6 – Data Type Audit
# The company says
# Age and AnnualIncome are stored incorrectly.
# Tasks
# Convert
# Age → int
# AnnualIncome → float
# Balance → float
# Target → string
# Print information.
age=df["Age"].astype("int")
age

0       58
1       65
2       56
3       55
4       66
        ..
1015    43
1016    25
1017    49
1018    38
1019    62
Name: Age, Length: 1020, dtype: int32

In [131]:
anual=df["AnnualIncome"].astype("float")
anual

0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018    112358.0
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64

In [133]:
bal=df["Balance"].astype("float")
bal

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [135]:
tar=df["Target"].astype("str")
tar

0        Stay
1       Churn
2        Stay
3       Churn
4       Churn
        ...
1015     Stay
1016    Churn
1017     Stay
1018     Stay
1019    Churn
Name: Target, Length: 1020, dtype: object

In [141]:
# Challenge 7 – Customer Analytics
# Create a new DataFrame that
# • removes Segment
# • removes Geography
# • removes duplicate rows
# Display
# • first 10 rows
# • dataset information
# • statistical summary
df1.drop(["Segment","Geography"],axis=1)

,CustomerID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,EmployeeGender,PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,Male,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,Male,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Male,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,Male,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,Other,Churn
...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,Other,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,NaN,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Female,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Other,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Other,Churn

In [147]:
df1.drop_duplicates()

,CustomerID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [149]:
df1.head(10)

,CustomerID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn

In [153]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0    CustomerID      1020 non-null   int64
 1   EmployeeAge      970 non-null    float64
 2   Salary           967 non-null    float64
 3   Spending         1020 non-null   int64
 4   CreditScore      1020 non-null   int64
 5   Balance          969 non-null    float64
 6   Tenure           1020 non-null   int64
 7   Geography        969 non-null    object
 8   EmployeeGender   968 non-null    object
 9   Segment          969 non-null    object
 10  PromotionStatus  1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 127.9+ KB

In [157]:
df1.describe()

,CustomerID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [159]:
# Challenge 8 – ML Dataset Preparation
# Prepare a machine learning dataset.
# Perform
# • Remove duplicates
# • Remove CustomerID
# • Remove Segment
# • Fill missing values
# • Rename Target to Output
# Finally
# Display
# head()
# info()
# describe()
# value_counts(Output)
df2=pd.read_csv("C:\\Users\\vaish\\Downloads\\Task_dataset.csv")

df2.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [163]:
df2.drop(["CustomerID","Segment"],axis=1)

KeyError: "['CustomerID', 'Segment'] not found in axis"

In [219]:
df2.rename(columns={"Target":"Output"},inplace=True)

In [221]:
df2.isna().sum()

 CustomerID      0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Output           0
dtype: int64

In [223]:
df2.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn

In [225]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Output        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 95.6+ KB

In [227]:
df2.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [229]:
df2["Output"].value_counts()

Output
Churn    515
Stay     505
Name: count, dtype: int64

In [231]:
# Challenge 9 – Column Transformation
# Create these new columns
# NetWorth = Balance + AnnualIncome
# AgeAfterRetirement = Age + 20
# DoubleCreditScore = CreditScore * 2
# IncomePerMonth = AnnualIncome / 12
# Then
# Display first 15 rows.
df2["NetWorth"]=df2["Balance"]+df2["AnnualIncome"]
df2["NetWorth"]

0             NaN
1       169320.54
2       170159.92
3       232553.88
4       184221.46
          ...
1015    233973.03
1016    179002.07
1017    135912.09
1018          NaN
1019          NaN
Name: NetWorth, Length: 1020, dtype: float64

In [233]:
df2["AgeAfterRetirement"]=df2["Age"]+20
df2["AgeAfterRetirement"]

0       78.0
1       85.0
2       76.0
3       75.0
4       86.0
        ...
1015    63.0
1016    45.0
1017    69.0
1018    58.0
1019    82.0
Name: AgeAfterRetirement, Length: 1020, dtype: float64

In [235]:
df2["DoubleCreditScore"]=df["CreditScore"]*2
df2["DoubleCreditScore"]

0       1162
1       1464
2       1006
3        926
4        788
        ...
1015    1288
1016     606
1017    1626
1018    1444
1019     860
Name: DoubleCreditScore, Length: 1020, dtype: int64

In [237]:
df2["IncomePerMonth"]=df2["AnnualIncome"]/12
df2["IncomePerMonth"]

0        4098.666667
1       13580.333333
2        2246.333333
3        7743.833333
4        9019.666667
            ...
1015    14468.333333
1016     4540.833333
1017     6838.500000
1018             NaN
1019     8125.333333
Name: IncomePerMonth, Length: 1020, dtype: float64

In [241]:
df2.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay,138635.62,89.0,1540,2615.833333
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn,220598.72,78.0,1782,15178.416667
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay,269157.73,87.0,1076,7988.416667
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay,104539.41,61.0,1326,5219.833333
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn,286507.98,42.0,950,14973.333333
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay,231695.03,NaN,1740,15647.666667
11,10012,69.0,102694.0,26790,574,13237.72,9,France,Female,Retail,Churn,115931.72,89.0,1148,8557.833333
12,10013,59.0,150870.0,26428,769,28574.32,2,USA,Other,SME,Stay,179444.32,79.0,1538,12572.500000
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay,174562.77,72.0,1796,7406.333333
14,10015,26.0,153569.0,32843,393,151156.43,1,USA,Other,Retail,Churn,304725.43,46.0,786,12797.416667

In [243]:
# Challenge 10 – Company Report
# Display
# • first five rows
# • last five rows
# • ten random rows
# • dataset information
# • descriptive statistics
# Finally rename
# Target → Customer_Status
df2.head(5)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667

In [245]:
df2.tail(5)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,233973.03,63.0,1288,14468.333333
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,179002.07,45.0,606,4540.833333
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,135912.09,69.0,1626,6838.500000
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,NaN,58.0,1444,NaN
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,NaN,82.0,860,8125.333333

In [247]:
df2.sample(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
414,10415,33.0,32053.0,31417,672,76595.89,2,USA,Male,SME,Stay,108648.89,53.0,1344,2671.083333
615,10616,44.0,164730.0,37040,794,35743.92,8,Germany,Female,Corporate,Stay,200473.92,64.0,1588,13727.500000
797,10798,22.0,176830.0,7626,688,65481.65,10,France,Male,Retail,Stay,242311.65,42.0,1376,14735.833333
979,10980,20.0,193597.0,4083,545,50596.58,6,UK,Other,SME,Stay,244193.58,40.0,1090,16133.083333
87,10088,59.0,90800.0,40864,851,154928.29,7,Canada,Other,SME,Stay,245728.29,79.0,1702,7566.666667
777,10778,37.0,105809.0,9890,400,164427.70,8,France,Male,Retail,Churn,270236.70,57.0,800,8817.416667
405,10406,43.0,41607.0,42478,849,107531.07,2,UK,Male,Corporate,Stay,149138.07,63.0,1698,3467.250000
70,10071,52.0,41122.0,9568,454,NaN,2,France,Male,Retail,Churn,NaN,72.0,908,3426.833333
403,10404,61.0,65290.0,31368,374,3337.88,1,India,Female,Retail,Churn,68627.88,81.0,748,5440.833333
725,10726,63.0,25633.0,3105,553,184454.02,4,UK,Female,Corporate,Stay,210087.02,83.0,1106,2136.083333

In [249]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0    CustomerID         1020 non-null   int64
 1   Age                 970 non-null    float64
 2   AnnualIncome        967 non-null    float64
 3   Spending            1020 non-null   int64
 4   CreditScore         1020 non-null   int64
 5   Balance             969 non-null    float64
 6   Tenure              1020 non-null   int64
 7   Geography           969 non-null    object
 8   Gender              968 non-null    object
 9   Segment             969 non-null    object
 10  Output              1020 non-null   object
 11  NetWorth            920 non-null    float64
 12  AgeAfterRetirement  970 non-null    float64
 13  DoubleCreditScore   1020 non-null   int64
 14  IncomePerMonth      967 non-null    float64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB

In [251]:
df2.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000,920.000000,970.000000,1020.000000,967.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765,209641.594380,64.249485,1205.319608,9375.494054
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330,74287.727616,15.521935,353.121379,4358.613545
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,33432.390000,38.000000,600.000000,1685.583333
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000,156965.307500,50.250000,881.500000,5512.416667
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000,209204.760000,64.000000,1214.000000,9363.166667
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000,261256.997500,78.000000,1514.500000,13166.708333
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,390628.400000,90.000000,1800.000000,16663.916667

In [255]:
df2.rename(columns={"Target":"Customer_Status"},inplace=True)
df2

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,233973.03,63.0,1288,14468.333333
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,179002.07,45.0,606,4540.833333
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,135912.09,69.0,1626,6838.500000
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,NaN,58.0,1444,NaN
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,NaN,82.0,860,8125.333333

In [259]:
# Challenge 11 – Missing Value Report
# Create a report showing
# • Total missing values
# • Numerical columns
# • Mean of Balance
# • Median of Age
# • Fill missing values
# • Display information again
df2.isna().sum()

 CustomerID             0
Age                    50
AnnualIncome           53
Spending                0
CreditScore             0
Balance                51
Tenure                  0
Geography              51
Gender                 52
Segment                51
Output                  0
NetWorth              100
AgeAfterRetirement     50
DoubleCreditScore       0
IncomePerMonth         53
dtype: int64

In [263]:
df2.select_dtypes(include=["int","float"]).columns

Index([' CustomerID ', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure', 'NetWorth', 'AgeAfterRetirement',
       'DoubleCreditScore', 'IncomePerMonth'],
      dtype='object')

In [269]:
bal_mean=df["Balance"].mean()
bal_mean
df["Balance"]=df["Balance"].fillna(bal_mean)
df["Balance"]

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [273]:
med_age=df["Age"].median()
med_age
df["Age"]=df["Age"].fillna(med_age)
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [275]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0    CustomerID         1020 non-null   int64
 1   Age                 970 non-null    float64
 2   AnnualIncome        967 non-null    float64
 3   Spending            1020 non-null   int64
 4   CreditScore         1020 non-null   int64
 5   Balance             969 non-null    float64
 6   Tenure              1020 non-null   int64
 7   Geography           969 non-null    object
 8   Gender              968 non-null    object
 9   Segment             969 non-null    object
 10  Output              1020 non-null   object
 11  NetWorth            920 non-null    float64
 12  AgeAfterRetirement  970 non-null    float64
 13  DoubleCreditScore   1020 non-null   int64
 14  IncomePerMonth      967 non-null    float64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB

In [285]:
# Challenge 12 – Customer Classification
# Count
# Stay

# Churn
# Then
# Rename
# Target → Customer_Class
# Convert it into string.

df3=pd.read_csv("C:\\Users\\vaish\\Downloads\\Task_dataset.csv")

df3.rename(columns={"Target":"Customer_Class"},inplace=True)
df3

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Class
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [291]:
df3["Customer_Class"].astype("str")

0        Stay
1       Churn
2        Stay
3       Churn
4       Churn
        ...
1015     Stay
1016    Churn
1017     Stay
1018     Stay
1019    Churn
Name: Customer_Class, Length: 1020, dtype: object

In [297]:
# Challenge 13 – Sales Department
# Balance → AccountBalance
# AnnualIncome → Salary
# CreditScore → Score
# Add prefix
# Sales_
# Then
# Display
# sample(20)
df3.rename(columns={"Balance":"AccountBalance","AnnualIncome":"Salary","CreditScore":"Score"},inplace=True)
df3

,CustomerID,Age,Salary,Spending,Score,AccountBalance,Tenure,Geography,Gender,Segment,Customer_Class
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [299]:
df3.add_prefix("Sales_")

,Sales_ CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Customer_Class
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [301]:
df3.sample(20)

,CustomerID,Age,Salary,Spending,Score,AccountBalance,Tenure,Geography,Gender,Segment,Customer_Class
913,10914,49.0,189026.0,16539,329,23870.93,4,Canada,NaN,SME,Churn
464,10465,23.0,144143.0,8069,615,156975.31,7,Canada,Other,Corporate,Stay
292,10293,NaN,73844.0,47483,897,97765.59,8,Canada,Male,Corporate,Stay
603,10604,29.0,155434.0,27071,877,127524.54,10,UK,Male,Retail,Stay
523,10524,40.0,134744.0,41250,574,175695.11,1,NaN,Female,Retail,Churn
500,10501,21.0,186303.0,38745,894,188860.20,1,Canada,Male,SME,Churn
148,10149,37.0,149138.0,8110,399,46960.01,8,USA,Female,Corporate,Churn
61,10062,48.0,64483.0,43678,386,56757.28,10,France,Other,NaN,Churn
240,10241,47.0,198286.0,34405,652,25666.92,8,France,Other,Retail,Stay
591,10592,NaN,180965.0,45337,469,151441.21,2,Canada,Male,Retail,Churn
481,10482,66.0,155397.0,25004,357,103053.94,2,India,Female,SME,Churn
459,10460,53.0,44406.0,22647,794,140900.93,6,NaN,Male,SME,Stay
323,10324,57.0,146669.0,43706,799,3146.35,8,Germany,Female,Retail,Churn
325,10326,61.0,132872.0,12248,409,183609.77,8,USA,Male,Retail,Churn
617,10618,46.0,62413.0,7071,519,101668.71,5,Germany,Other,SME,Stay
142,10143,68.0,NaN,24476,843,100358.95,4,USA,Female,Corporate,Stay
894,10895,36.0,139518.0,11402,464,142362.43,4,USA,Male,SME,Churn
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
130,10131,32.0,43692.0,28940,400,152073.94,1,Canada,Male,SME,Churn
468,10469,53.0,35986.0,25869,835,83726.41,8,France,Female,SME,Stay

In [303]:
# Challenge 14 – Interview Challenge
# Without creating another DataFrame,
# perform
# • remove duplicates
# • rename Target
# • fill missing values
# • convert Balance to float
# • display summary
df3.drop_duplicates()

,CustomerID,Age,Salary,Spending,Score,AccountBalance,Tenure,Geography,Gender,Segment,Customer_Class
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [313]:
df1.rename(columns={"Target":"Exited"},inplace=True)
df1

,CustomerID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [317]:
df["Balance"]=df["Balance"].fillna(method="ffill")
df["Balance"]

C:\Users\vaish\AppData\Local\Temp\ipykernel_26016\467515104.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Balance"]=df["Balance"].fillna(method="ffill")

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [319]:
df["Balance"].astype("float")

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [321]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Output        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 95.6+ KB

In [329]:
# Challenge 15 – Data Engineer Task
# Load the dataset.
# Create another DataFrame containing only numeric columns.
# Drop
# CustomerID
# Target
# Display summary.
num=df3.select_dtypes(["int","float"])
num

       CustomerID    Age    Salary  Spending  Score  AccountBalance  Tenure
0            10001  58.0   49184.0      2139    581             NaN       2
1            10002  65.0  162964.0      6197    732         6356.54       1
2            10003  56.0   26956.0     37281    503       143203.92       8
3            10004  55.0   92926.0       925    463       139627.88       5
4            10005  66.0  108236.0      7198    394        75985.46       5
...            ...   ...       ...       ...    ...             ...     ...
1015         10450  43.0  173620.0      7121    644        60353.03       2
1016         10753  25.0   54490.0     13794    303       124512.07       4
1017         10810  49.0   82062.0     47170    813        53850.09       8
1018         10267  38.0       NaN     10424    722       138100.05       6
1019         10059  62.0   97504.0     36833    430             NaN      10

[1020 rows x 7 columns]

In [499]:
df7

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [503]:
df7=pd.read_csv("C:\\Users\\vaish\\Downloads\\Task_dataset.csv")

df7.drop(["Target"],axis=1)
df7.drop({"CustomerID"},axis=1)

KeyError: "['CustomerID'] not found in axis"

In [343]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0    CustomerID     1020 non-null   int64
 1   Age             970 non-null    float64
 2   Salary          967 non-null    float64
 3   Spending        1020 non-null   int64
 4   Score           1020 non-null   int64
 5   AccountBalance  969 non-null    float64
 6   Tenure          1020 non-null   int64
 7   Geography       969 non-null    object
 8   Gender          968 non-null    object
 9   Segment         969 non-null    object
 10  Customer_Class  1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [345]:
# Challenge 16 – Mixed Cleaning
# Perform

# Sumit Sir Notes
# drop_duplicates()
# fillna()
# astype()
# rename()
# head()
# info()
# using only one DataFrame variable.
df3.drop_duplicates()

,CustomerID,Age,Salary,Spending,Score,AccountBalance,Tenure,Geography,Gender,Segment,Customer_Class
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [351]:
age_mean=int(df["Age"].mean())
age_mean
df["Age"]=df["Age"].fillna(age_mean)
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [353]:
df["Age"]=df["Age"].astype("int")

In [355]:
df.rename(columns={"Gender":"Sex"})

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Sex,Segment,Output
0,10001,58,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38,112358.0,10424,722,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn

In [357]:
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output
0,10001,58,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn

In [359]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           1020 non-null   int32
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Output        1020 non-null   object
dtypes: float64(2), int32(1), int64(4), object(4)
memory usage: 91.6+ KB

In [361]:
# Challenge 17 – Real Company Dataset
# Manager asks
# Remove duplicate records

# Fill missing values
# Rename all business columns
# Add company prefix
# Display summary
# Display target counts
df.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output
0,10001,58,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34,81731.0,40980,761,181465.650000,5,Germany,Other,SME,Stay
996,10997,47,42475.0,1176,780,26640.990000,5,France,Female,SME,Stay
997,10998,31,120531.0,46929,733,147220.820000,4,India,Male,SME,Stay
998,10999,21,33661.0,22314,540,94186.480000,5,NaN,Other,SME,Stay
999,11000,63,31930.0,851,559,100908.400000,6,UK,Female,NaN,Stay

In [365]:
df["AnnualIncome"]=df['AnnualIncome'].fillna(method="ffill")
df["AnnualIncome"]

C:\Users\vaish\AppData\Local\Temp\ipykernel_26016\3127670552.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["AnnualIncome"]=df['AnnualIncome'].fillna(method="ffill")

0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018    112358.0
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64

In [367]:
df.add_prefix("Google_")

,Google_ CustomerID,Google_Age,Google_AnnualIncome,Google_Spending,Google_CreditScore,Google_Balance,Google_Tenure,Google_Geography,Google_Gender,Google_Segment,Google_Output
0,10001,58,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38,112358.0,10424,722,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn

In [369]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           1020 non-null   int32
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Output        1020 non-null   object
dtypes: float64(2), int32(1), int64(4), object(4)
memory usage: 91.6+ KB

In [389]:
df4=pd.read_csv("C:\\Users\\vaish\\Downloads\\Task_dataset.csv")
df4["Target"].value_counts()

Target
Churn    515
Stay     505
Name: count, dtype: int64

In [391]:
# Challenge 18 – Customer Summary
# Generate
# Mean Balance
# Median Balance
# Mean Age
# Median AnnualIncome

# Then
# fill missing values using these statistics.
mean_bal=df4["Balance"].mean()
mean_bal
df4["Balance"]=df4["Balance"].fillna(mean_bal)
df4["Balance"]

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [393]:
med_bal=df4["Balance"].median()
med_bal
df4["Balance"]=df4["Balance"].fillna(med_bal)
df4["Balance"]

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [395]:
mean_age=df4["Age"].mean()
mean_age
df4["Age"]=df4["Age"].fillna(mean_age)
df4["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [397]:
med_age=df4["Age"].median()
med_age
df4["Age"]=df4["Age"].fillna(med_age)
df4["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [399]:
med_anual=df4["AnnualIncome"].median()
med_anual
df4["AnnualIncome"]=df4["AnnualIncome"].fillna(med_anual)
df4["AnnualIncome"]

0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018    112358.0
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64

In [401]:
# Challenge 19 – Transformation Challenge
# Create
# Income_in_Lakhs
# Balance_in_Lakhs

# SeniorCitizen
# HighCreditScore
# where
# SeniorCitizen = Age + 0
# HighCreditScore = CreditScore * 1
# (No conditional statements.)
df4['Income_in_Lakhs']=df4["AnnualIncome"]>100000
df4['Income_in_Lakhs']

0       False
1        True
2       False
3       False
4        True
        ...
1015     True
1016    False
1017    False
1018     True
1019    False
Name: Income_in_Lakhs, Length: 1020, dtype: bool

In [403]:
df4['Balance_in_Lakhs']=df4["Balance"]>100000
df4['Balance_in_Lakhs']

0       False
1       False
2        True
3        True
4       False
        ...
1015    False
1016     True
1017    False
1018     True
1019    False
Name: Balance_in_Lakhs, Length: 1020, dtype: bool

In [409]:
df["SeniorCitizen"]=df["Age"]+0
df["SeniorCitizen"]

0       58
1       65
2       56
3       55
4       66
        ..
1015    43
1016    25
1017    49
1018    38
1019    62
Name: SeniorCitizen, Length: 1020, dtype: int32

In [411]:
df4["HighCreditScore"]=df4["CreditScore"]*1
df4["HighCreditScore"]

0       581
1       732
2       503
3       463
4       394
       ...
1015    644
1016    303
1017    813
1018    722
1019    430
Name: HighCreditScore, Length: 1020, dtype: int64

In [449]:
# Challenge 20 – Final Interview Project
# Your manager gives you a dirty customer dataset.
# Prepare the final dataset.
# Requirements
# Load dataset
# Check information
# Find missing values
# Remove duplicates
# Rename
# CustomerID
# AnnualIncome
# CreditScore
# Target

# Convert
# Age

# Sumit Sir Notes
# AnnualIncome
# Balance

# Fill missing values
# Remove
# Segment
# CustomerID
# Create new columns
# TotalMoney = Balance + AnnualIncome
# AgeAfter5Years = Age + 5
# MonthlyIncome = AnnualIncome / 12
# CreditScoreDouble = CreditScore * 2Display
# • Head
# • Tail
# • Sample
# • Describe
# • Target counts
# • Final information
df5=pd.read_csv("C:\\Users\\vaish\\Downloads\\Task_dataset.csv")
df5
df6=pd.read_csv("C:\\Users\\vaish\\Downloads\\Task_dataset.csv")

In [415]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [425]:
df5.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [429]:
df5.isnull().sum()

 CustomerID      0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [431]:
df5.rename(columns={"CustomerID":"Customer_ID","AnnualIncome":"Annual_Income","CreditScore":"Credit_Score","Target":"Exited"},inplace=True)
df5

,CustomerID,Age,Annual_Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,Segment,Exited
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [437]:
sel_int=df5.select_dtypes(include=["int"]).columns
for col in sel_int:
    df5[col].astype("float")

In [441]:
df5["Segment"].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
1015    False
1016    False
1017    False
1018    False
1019     True
Name: Segment, Length: 1020, dtype: bool

In [453]:
df6["CustomerID"].isnull()

KeyError: 'CustomerID'

In [455]:
df5["TotalMoney"]=df5["Balance"]+df["AnnualIncome"]
df5["TotalMoney"]

0             NaN
1       169320.54
2       170159.92
3       232553.88
4       184221.46
          ...
1015    233973.03
1016    179002.07
1017    135912.09
1018    250458.05
1019          NaN
Name: TotalMoney, Length: 1020, dtype: float64

In [459]:
df["AgeAfter5Years"]=df["Age"]+5
df["AgeAfter5Years"]

0       63
1       70
2       61
3       60
4       71
        ..
1015    48
1016    30
1017    54
1018    43
1019    67
Name: AgeAfter5Years, Length: 1020, dtype: int32

In [461]:
df5["MonthlyIncome"]=df5["AnnualIncome"]/12
df5["MonthlyIncome"]

0        4098.666667
1       13580.333333
2        2246.333333
3        7743.833333
4        9019.666667
            ...
1015    14468.333333
1016     4540.833333
1017     6838.500000
1018             NaN
1019     8125.333333
Name: MonthlyIncome, Length: 1020, dtype: float64

In [471]:
df5["CreditScoreDouble"]=df5["CreditScore"]*2
df5["CreditScoreDouble"]

0       1162
1       1464
2       1006
3        926
4        788
        ...
1015    1288
1016     606
1017    1626
1018    1444
1019     860
Name: CreditScoreDouble, Length: 1020, dtype: int64

In [473]:
df5.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,TotalMoney,MonthlyIncome,CreditScoreDouble
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,4098.666667,1162
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,13580.333333,1464
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,2246.333333,1006
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,7743.833333,926
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,9019.666667,788

In [475]:
df5.tail()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,TotalMoney,MonthlyIncome,CreditScoreDouble
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,233973.03,14468.333333,1288
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,179002.07,4540.833333,606
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,135912.09,6838.500000,1626
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,250458.05,NaN,1444
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,NaN,8125.333333,860

In [477]:
df5.sample()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,TotalMoney,MonthlyIncome,CreditScoreDouble
1011,10457,44.0,63604.0,27633,804,176354.13,5,Germany,Female,Retail,Stay,239958.13,5300.333333,1608

In [479]:
df5.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,TotalMoney,MonthlyIncome,CreditScoreDouble
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000,969.000000,967.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765,210084.415955,9375.494054,1205.319608
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330,73673.997276,4358.613545,353.121379
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,33432.390000,1685.583333,600.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000,157281.520000,5512.416667,881.500000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000,210068.520000,9363.166667,1214.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000,261850.260000,13166.708333,1514.500000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,390628.400000,16663.916667,1800.000000

In [481]:
df5["Target"].value_counts()

Target
Churn    515
Stay     505
Name: count, dtype: int64

In [483]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0    CustomerID        1020 non-null   int64
 1   Age                970 non-null    float64
 2   AnnualIncome       967 non-null    float64
 3   Spending           1020 non-null   int64
 4   CreditScore        1020 non-null   int64
 5   Balance            969 non-null    float64
 6   Tenure             1020 non-null   int64
 7   Geography          969 non-null    object
 8   Gender             968 non-null    object
 9   Segment            969 non-null    object
 10  Target             1020 non-null   object
 11  TotalMoney         969 non-null    float64
 12  MonthlyIncome      967 non-null    float64
 13  CreditScoreDouble  1020 non-null   int64
dtypes: float64(5), int64(5), object(4)
memory usage: 111.7+ KB